### ISSUE TITLE
Example service call syntax error

### ISSUE THREAD

**Issue by joeio** [home-assistant/iOS#1146]
In the app under **App Configuration** -> **Notifications** -> **Synced Categories** -> _Category_Name_, there's an **Example Service Call** that goes like this:

```
service: notify.mobile_app_#name_here
data:
  push:
    category: ALARM
  action_data:
    # see example trigger in action
    # value will be in fired event

  # url can be absolute path like:
  # "http://example.com/url"
  # or relative like:
  # "/lovelace/dashboard"

  # pick one of the following styles:

  # always open when opening notification
  url: "/lovelace/dashboard"

  # open a different url per action
  # use "_" as key for no action chosen
  url:
  - "_": "http://example.com/fallback"
  - "SOUND_ALARM": "http://example.com/url"
  - "SILENCE_ALARM": "http://example.com/url"
```

However, the last part using multiple URLs should be in the form of a dictionary, as follow:

```
url:
    "_": "http://example.com/fallback"
    "SOUND_ALARM": "http://example.com/url"
     "SILENCE_ALARM": "http://example.com/url"
```
