### ISSUE TITLE
Unrecoverable state when action opens a page which doesn't exist

### ISSUE THREAD

**Issue by sebr** [home-assistant/iOS#1172]
**iOS device model, version and app version**

Model Name: iPhone XR
Software Version: 14.2
App version: 2020.6.1 (2)

**Home Assistant Core Version**
0.115.6

**Describe the bug**
When opening a Lovelace page from an iOS notification, if the page does not exist then the app displays a 404 page which cannot be escaped (aside from a forced restart of the app).

**To Reproduce**
Fire a notification to an iOS device with a payload as such as:
```
- service: notify.sebs_iphone
   data:
     message: "test"
     data:
       url: "/fail"
```

**Expected behavior**
The app opens the default lovelace dashboard. This is consistent with web.

**Screenshots**
![IMG_63263FE3B750-1](https://user-images.githubusercontent.com/81972/95418809-01796c80-0984-11eb-8daf-6fc508a770d5.jpeg)
