### ISSUE TITLE
On Load of app, Do Something eg Reset Badge

### ISSUE THREAD

**Issue by townsmcp** [home-assistant/iOS#1204]
**Is your feature request related to a problem? Please describe.**
I have been looking online but cant see a answer to my question; is there a way to do something when loading Companion App on iOS? eg, when I open the app, clear badges? I understand I can send a clear badge notificaiton from HA, however, the bahviour on other apps is, when there is a notification/badge update, if you load the app this gets cleared. I also understand I can manually go to the settings and clear the badges however for no tech people, this might be a step to far to go into settings and clear.

**Describe the solution you'd like**
When opening Companion App, clear the badges 

**Additional context**

**Comment by TomBrien** [comment]
You should be able to use the [`ios.became_active`](https://companion.home-assistant.io/docs/integrations/app-events)to trigger an automation. You could then, for example send the `clear_badge` message to clear the app badge.

**Comment by townsmcp** [comment]
@TomBrien thank you. Would that go into Integrations => Actions from in the companion app?

**Comment by TomBrien** [comment]
No. You'd need to make an automation on home assistant that uses that event as it's trigger. It would look something like (in YAML):

```yaml
automation:
  - alias: Reset App Badge
    trigger:
      - platform: event
        event_type: ios.became_active
    action:
      service: notify.mobile_app_DEVICE_NAME
      data:
        message: clear_badge
```
I haven't had a chance to check that but off top of my head looks ok.
