### ISSUE TITLE
API sendPushNotification 500 error with notification with "sound" data in request

### ISSUE THREAD

**Issue by gonzalezcalleja** [home-assistant/iOS#1229]
**Device model, version and app version**
2020.7(7) but fails with any use of the endpoint: https://mobile-apps.home-assistant.io/api/sendPushNotification

Model Name: 
macOS Version: 
App Version: 2020.7(7) 
Safari Version:

**Home Assistant Core Version**
0.116.4

**Describe the bug**
Sending a notification to macOS App with "sound" in data request, the endpoint in https://mobile-apps.home-assistant.io/api/sendPushNotification return an Internal Server Error (500).

**To Reproduce**
Call service notify.mobile_app_[device name] with this data:

```
    message: "Test message"
      data:
        attachment:
          content-type: jpeg
        push:
          category: camera-doorbell
          thread-id: "doorbell-notification-group"
          sound:
            name: default
            volume: 0
        entity_id: camera.calle
```

Or make a POST call to the endpoint: https://mobile-apps.home-assistant.io/api/sendPushNotification
like this:

```
{
  "message": "Llamada Videoportero",
  "data": {
    "attachment": {
      "content-type": "jpeg"
    },
    "push": {
      "category": "camera-doorbell",
      "thread-id": "doorbell-notification-group",
      "sound": {
        "name": "default",
        "volume": 0
      }
    },
    "entity_id": "camera.calle"
  },
  "push_token": "(valid push token)",
  "registration_info": {
    "app_id": "io.robbie.HomeAssistant",
    "app_version": "2020.7 (7)",
    "os_version": "10.15.7"
  }
}
```

Without 

```
 "sound": {
        "name": "default",
        "volume": 0
      }
```

is ok but with "sound" field present, endpoint return a 500 error.

**Expected behavior**
A notification in macOS App.
