### ISSUE TITLE
Duplicate sensor entities created over time

### ISSUE THREAD

**Issue by dwradcliffe** [home-assistant/iOS#1261]
**Device model, version and app version**

Model Name: MacBook Pro (16-inch, 2019)
macOS Version: 10.15.6 (19G2021)
App Version: 2020.7 (10)
Safari Version: Version 14.0 (15610.1.28.1.9, 15610)

**Home Assistant Core Version**
0.117.1

**Describe the bug**
I've been running the mac app for a couple weeks and every few days some of my sensors get re-created using new entities and names. The 2 examples I have are a USB camera and USB audio device. Both are plugged in via the same USB path which hasn't changed. The result is duplicate entities and each time the "correct" one changes names so I can't ever use it.

**To Reproduce**

Run the app as normal for a few weeks and observe entities for USB devices (camera and audio?).

**Expected behavior**

After first creating entities, they shouldn't ever change.

**Screenshots**

![image](https://user-images.githubusercontent.com/118850/98041114-6db68700-1def-11eb-9176-0b8fdf152d2c.png)
![image](https://user-images.githubusercontent.com/118850/98041158-7c9d3980-1def-11eb-8df6-c276915e7c29.png)

**Additional context**

Happy to give any more details if needed.

**Comment by dwradcliffe** [comment]
Similar to https://github.com/home-assistant/iOS/issues/1216 but I didn't change the name of my computer or any devices.

**Comment by jelmerkk** [comment]
I have the same issue.

**Comment by zacwest** [comment]
This is proving a difficult one to nail down. The bigger issue is that the system itself actually believes these are new devices. For example, I have `Razer Kiyo #3` attached, which is distinct from `#2` and the first one. They're all the same camera, but the system doesn't think so. The only information we seem to reliably know are the names and unique IDs, both of which are lies here.

**Comment by dwradcliffe** [comment]
Yep that matches my experience too. I haven't been able to find any clues about why the system thinks it's different.

**Comment by dwradcliffe** [comment]
I have a temporary workaround using a template binary sensor to show on if any of the entities are on:

```yaml
binary_sensor:
  - platform: template
    sensors:
      davids_logitech_camera:
        friendly_name: David's MacBook Pro Logitech Brio (Camera)
        value_template: >
          {% set ns = namespace(found=false) %}
          {%- for state in states.binary_sensor if "brio" in state.entity_id and "camera" in state_attr(state.entity_id, "icon") and state.state == "on" %}
            {% set ns.found = true %}
          {%- endfor %}
          {{ ns.found }}
```
