### ISSUE TITLE
HLS stream in notification does not start

### ISSUE THREAD

**Issue by hanzoh** [home-assistant/iOS#1276]
**iOS device model, version and app version**

Model Name: iPhone Xs
Software Version: iOS 14.2
App version: 2020.7 (11)

**Home Assistant Core Version**

0.117.6

**Describe the bug**
When sending a notification with a RTSP camera's video feed and opening it on the iPhone, the video tries to load but then times out to a Play button.

**To Reproduce**
configuration.yaml:
```yaml
camera:
  - platform: generic
    name: Front Door
    still_image_url: http://192.168.1.103/snap.jpeg
    verify_ssl: false
    stream_source: rtsp://192.168.1.103:554/s0
```

**Expected behavior**
Camera stream starts in notification

**Screenshots**

**Additional context**

Home Assistant runs in the official Docker container and external access is done via Traefik reverse proxy.
When accessing the camera stream via a picture-entity lovelace card, it works fine using mobile data and the external URL configured in Home Assistant Companion.

**Comment by TomBrien** [comment]
Could you show us the automation code/service call you are using to send the notification please

**Comment by hanzoh** [comment]
```yaml
    - service: notify.mobile_app_iphone
      data:
        message: "\uD83D\uDD14 Front Door"
        data:
          url: /lovelace/cameras
          attachment:
            content-type: jpeg
          push:
            thread-id: "frontdoor"
            category: camera
          entity_id: camera.front_door
```

**Comment by zacwest** [comment]
The easiest way to see what's going on is going to be looking at logs. Reproduce the video failing it play and then in App Configuration > Export Logs, grab the relevant logs timestamp-wise. It shouldn't be more than a few dozen lines.

The stream URL that the app loads is identical to the URL that the more-info version of a camera entity shows up as in lovelace. Please check your HA logs for anything like:

```
ERROR (stream_worker) [homeassistant.components.stream.worker] Error opening stream rtsp://…
```

You can also try adding a random external RTSP stream like the following:

```yaml
camera:
  - platform: generic
    name: Outside
    still_image_url: https://picsum.photos/1024/768
    stream_source: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov
```

Using your notification call and the camera defined above, I have no issues playing the stream in the notification.
