### ISSUE TITLE
iBeacon enter triggered each time screen is awaken

### ISSUE THREAD

**Issue by cadavre** [home-assistant/iOS#1369]
**iOS device model, version and app version**

Model Name: iPhone XR
Software Version: iOS 14.3
App version: 2021.1 (5)

**Home Assistant Core Version**

Home Assistant 2021.1.0

**Describe the bug**

This one is super strange. I have a single iBeacon in my "home" location, placed so I can trigger home zone enter faster than with "significant location change".

This is simply done with customized home zone, with:

```yaml
# customize.yaml

zone.home:
  track_ios: true
  beacon:
    uuid: E2XXXXB5-XXXB-4XXX-XXX0-D0XXXXX096E0
    major: 1
    minor: 256
```

To test things out I enabled notifications on iBeacon enter in HA app. Now – it doesn't matter if I'm in range or 100km away from the beacon – each time I wake up the screen – I receive notification that I entered home zone and in HA – my person entity immediately is teleported to home zone coordinates.

Fun part is that if I disable iBeacon enter **notifications** – my person entity is not being set to home zone coordinates each time I wake up the screen (which is what I expect). *I haven't tested yet if this triggers correct zone enter by actually getting in iBeacon range.*

**To Reproduce**

Go to mobile app settings -> notifications -> enable notify on ibeacon zone enter.

**Expected behavior**

Trigger iBeacon enter only when I actually enter iBeacon range.

**Screenshots**

**Additional context**

Home zone definition:

```yaml
# configuration.yaml

zone:
  - name: Home
    latitude: nn.mmm
    longitude: xx.yyy
    radius: 150
    icon: mdi:home
```
