### ISSUE TITLE
Scenes with server-side customizations don't render in widgets

### ISSUE THREAD

**Issue by peterhajas** [home-assistant/iOS#1540]
I noticed this on the iOS, iPadOS, and macOS versions of the Companion app.

**Home Assistant Core Version**
2021.1.4

**Describe the bug**
Scenes with server-side customization don't render in widgets.

I have scenes with customizations in `customize.yaml`. For example, this one for my reading light:

```
scene.peter_reading:
  background_color: 'black'
  text_color: 'orange'
  icon_color: 'orange'
```

My colors render correctly in the menu items on the Mac, and the customization section of the widget, but they don't render in widgets on iOS, iPadOS, or macOS.

**To Reproduce**
- Create a scene
- Customize the scene with a `background_color`, `text_color`, and `icon_color`
- Pick this scene action for a widget

**Expected behavior**
- The scene renders in the widget with customizations applied.
