### ISSUE TITLE
Privacy and security to Today View Widget

### ISSUE THREAD

**Issue by hallenmaia** [home-assistant/iOS#1543]
**Is your feature request related to a problem? Please describe.**
Certain actions in the Today View widget should only be displayed when the device is unlocked by the user. There is a security risk, as it is possible to perform actions with the device locked. For example: Disarm Security Alarm.

Some widgets implement this functionality, such as "Usage time" and Fitness. They only display the skeleton when the device is locked.

![IMG_0794](https://user-images.githubusercontent.com/29228176/111550002-04ab2c80-875c-11eb-9407-9a2b3a392e02.jpeg)

WatchOS already implements this feature by default.

**Describe the solution you'd like**
Create a parameter to configure this option, as well as the authenticationRequired parameter in Actionable Notifications.

I believe that the Today View Widget will not allow this parameter to be configured per action. Then it would apply to all actions on the widget like this:

```
ios:
  actions:
    authenticationRequired: true
    - name: Fred
      background_color: "#000000"
      label:
        text: "Hello, World"
        color: "#ff0000"
      icon:
        icon: earth
        color: "#ffffff"
```
