### ISSUE TITLE
Storage entity with "%" as unit_of_measurement

### ISSUE THREAD

**Issue by ThomDietrich** [home-assistant/iOS#1551]
**Is your feature request related to a problem? Please describe.**

Not sure whether to call this a bug or a feature request, but rather an improvement suggestion.

I wonder about the structure of the storage endpoint. It's unit is "% available", which is questionable as a unit and does not nicely integrate with other "%" entities. Available is context, not unit. If any, the unit would be "percentage of storage" I suppose.

![image](https://user-images.githubusercontent.com/2870104/112506918-7d2e7080-8d8e-11eb-9e34-61c8dc31ba82.png)

**Describe the solution you'd like**

I suggest instead:

```yaml
Available: 849.38 GB
Available (Important): 859.45 GB
Available (Opportunistic): 847.10 GB
Total: 994.66 GB
unit_of_measurement: '%'                      # <--
friendly_name: ThLiliM1 Storage Available     # <--
icon: 'mdi:database'
```

Imho a breaking change of the entity name is not necessary and by adapting the friendly name the meaning of our value stays clear. Besides, I believe for storage the intuitive and well-known measure has always been % available, I do not expect any misconceptions here.

----
**Edit:**

While looking at it, why not add "Used" as another attribute for convenience?
