### ISSUE TITLE
Actionable Notifications on Apple Watch don't work

### ISSUE THREAD

**Issue by Shponzo** [home-assistant/iOS#1604]
Hi,

I'm using the beta HA app, and actionable notifications using my iPhone works perfectly.
The only problem is that when I want to use the action buttons on my Apple Watch, it doesn't trigger the event, so nothing happens.

**Comment by svaneepoel** [comment]
fyi, tried with both "mobile_app_notification_action" and "ios.notification_action_fired"

**Comment by TomBrien** [comment]
Can you post the automation you are using with the action?

**Comment by Shponzo** [comment]
> Can you post the automation you are using with the action?

Sure!
I'm just testing the iOS notification, so I use this in the services

```
service: notify.mobile_app_iphone_van_stef
data:
  message: Dit is een lange testzin
  title: test
  data:
    actions:
      - action: "ALARM"
        title: "Alarm"
```

And just try to let a light flash to see if it works:

`- id: '1619599642992'
  alias: Nieuwe automatisering
  description: ''
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: "SOUND_ALARM"
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id: light.lichtstrip_bureau
    data:
      flash: short`


Also tried it with NodeRed. But some problems. It seems like it doesn't trigger an event.
I create a debug node to see al events, but it doesn't show anything when I press the action on a push button.

Asked on Reddit and another user responded that he has the same errors using the new method (without category, beta app).
When we use the old method, it works perfectly.
