### ISSUE TITLE
iOS notification receives blank map/camera stream on iPhone(but works well on iPad)

### ISSUE THREAD

**Issue by left4taco** [home-assistant/iOS#1608]
**iOS device model, version and app version**

Model Name: iPhone 8 plus
Software Version: 14.4
App version: companion 2021.115

**But they both works find on iPad**

**Home Assistant Core Version**

Home assistant 2021.4.4

**Describe the bug**

I was trying to send a location or a camera stream to my phone so that I can get a preview in the 3D touch panel. The example I followed is from [official docs](https://companion.home-assistant.io/docs/notifications/dynamic-content#map).   
However, even tough the notification was delivered, there's nothing after I 3D-touched it. The screenshot is attached below.

One difference is that when pushing camera stream, the thumbnail image did show in the banner. (see below)

Pushing an image only works just fine. 

**To Reproduce**

The service I called is:
```yaml
service: notify.mobile_app_jojo
data:
  message: Something happened at home!
  data:
    push:
      category: map
    action_data:
      latitude: "40.785091"
      longitude: "-73.968285"
```
**Expected behavior**

The map preview shows in the dropdown panel.

**Screenshots**

Camera notification shows the thumbnail:  
![IMG_7576](https://user-images.githubusercontent.com/4816327/116645940-e59bdf00-a944-11eb-8c07-efc812eabda8.jpg)

Empty notification for both map and camera:  
![IMG_7575](https://user-images.githubusercontent.com/4816327/116644393-390c2e00-a941-11eb-9a5b-6230a3e8aa23.jpg)

**Additional context**
