### ISSUE TITLE
clear_notification command doesn't support setting badge to 0 at the same time

### ISSUE THREAD

**Issue by zacwest** [home-assistant/iOS#1623]
**iOS device model, version and app version**
Model Name: n/a
Software Version: n/a
App version: 2021.5

**Home Assistant Core Version**
n/a

**Describe the bug**
Sending a clear_notification call with a badge count gets the badge portion stripped, like so:

```yaml
- service: notify.mobile_app_<device>
  data:
    message: clear_notification
    data:
      tag: some_tag
      push:
      	badge: 0
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
