### ISSUE TITLE
clear_notification is not working

### ISSUE THREAD

**Issue by Vip0r** [home-assistant/iOS#1637]
Model Name: Iphone 8
Software Version: 14.4.2
App version: 2021.5.2

**Home Assistant Core Version**
core-2021.5.2

**Describe the bug**
clear_notification is not working as expected for ios

**To Reproduce**
Reproduced it by first using the following service calls to get some "test"-notifications for group "test"

service: notify.mobile_app_<devide_id>
data:
  message: "test"
  data:
    data:
      group: "test"

Afterwards i executed the following service calls to clear this notification

service: notify.mobile_app_<devide_id>
data:
  message: "clear_notification"
  data:
    tag: "test"

Messages however does not dissappear from the lockscreen

**Expected behavior**

If i get the documentation right the messages should disappear

**Comment by Vip0r** [comment]
Have tried the following to reproduce this

Using Developer Tools => Services => YAML Mode i have sent me some test messages including the tag with the following code:

```
service: notify.mobile_app_nds_iphone
data:
  title: test
  message: test
  data:
    tag: "testtag"
```

test-notification is shown immediately on my device. Afterwards i tried your code and used the following to clear the notification:

```
service: notify.mobile_app_nds_iphone
data:
  message: "clear_notification"
  data:
    tag: "testtag"
```

Unfortunately the message still does not disappear

**Comment by TomBrien** [comment]
> App version: 2021.5.2 

2021.5.2 is not a release number of the iOS app. I think you have the core version there. Can you confirm the in App Configuration>About you have `2021.5 (2021.150)` which is the latest release.

**Comment by Vip0r** [comment]
oh damn - my fault.

Have 2021.4.1 (2021.115) currently installed. Currently there is no update pending in the appstore - maybe i just have to wait that it will be avail. to me....

**Comment by misterdaan** [comment]
Model Name: iPhone 12
Software Version: 14.5.1
App version: 2021.5

Home Assistant Core Version
core-2021.5.5

I created scripts using SeanPM5's examples but clearing notifications is just not working. Not with the scripts, not with the developer helper tools, not with my own created automations. 

Here's the code I used:

```
notify_send:
  alias: 'Send a test message'
  sequence: 
    - service: notify.mobile_app_iphone_van_daan
      data:
        title: This is a test
        message: >-
          Testing testing testing
        data:
          tag: "ha-test"

notify_retract:
  alias: 'Clear the message'
  sequence: 
    - service: notify.mobile_app_iphone_van_daan
      data:
        message: "clear_notification"
        data:
          tag: "ha-test"
```

Executing notify_send does send a message, however executing notify_retract does nothing.
