### ISSUE TITLE
ultra slow badge reset using message: clear_badge

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/iOS#1644]
**iOS device model, version and app version**

Model Name:  iPhone 11 Pro
Software Version: 14.5.1
App version: 2021.5 (2021.150)

**Home Assistant Core Version**

2021.5.4
**Describe the bug**
using this automation:
```
  - alias: Mobile app - Dismiss
    id: Mobile app - Dismiss
    trigger:
      platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: DISMISS
#    condition:
#      >
#        {{trigger.event.data.action == 'DISMISS'}}
    action:
      service: notify.mobile_app_calltheboss
      data:
        message: clear_badge
```

the badge isn't reset <strike>immediately</strike> when action DISMISS is selected, while I can see it being triggered right away:

<img width="468" alt="Schermafbeelding 2021-05-25 om 13 05 40" src="https://user-images.githubusercontent.com/33354141/119499493-10702c00-bd67-11eb-8456-7bccc9f07f74.png">

<strike>I've now found that it is reset, but taking a very very long time, where before this seemed immediate. </strike>

first tried the commented version with the condition, which is what I use for the other 2 actions in a dedicated automation, and work fine:
```
  - alias: iOS - Garage door notification
    id: iOS - Garage door notification
    trigger:
      platform: event
      event_type: mobile_app_notification_action
    action:
      choose:
        - conditions: >
            {{trigger.event.data.action == 'DOOR_CLOSE'}}
          sequence:
            - service: cover.close_cover
              target:
                entity_id: cover.garage_deur
            - service: notify.mobile_app_calltheboss
              data:
                data:
                  push:
                    badge: 0
                title: Garage door
                message: Closed, badge reset

        - conditions: >
            {{trigger.event.data.action == 'DOOR_LEAVEBE'}}
          sequence:
            service: notify.mobile_app_calltheboss
            data:
              data:
                push:
                  badge: 1
              title: Garage door
              message: Ok, leave it be
```

**To Reproduce**
script:
```
  notify_garage_door_action:
    alias: Notify Garage door action
    mode: restart
    sequence:
      service: notify.mobile_app_calltheboss
      data:
        message: Garage staat open, wil je de deur sluiten?
        data:
          push:
            badge: 33
          actions:
            - action: DOOR_CLOSE
              title: 'Ja'
              destructive: true
            - action: DOOR_LEAVEBE
              title: 'Nee'
            - action: DISMISS
              title: Dismiss

```
is used for the actionable notification

**Expected behavior**
immediate badge reset
**Screenshots**

**Additional context**

seems the old way of doing things does still work immediately:

```
  - alias: iOS - Dismiss
    id: iOS - Dismiss
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: DISMISS
    condition: []
    action:
      service: notify.mobile_app_calltheboss
      data:
        title: iOS notification
        message: iOS - Dismissed, badge reset
        data:
          push:
            badge: 0
```

btw, I cant use the service in the services page in developer-tools either.
[Posted this in the community](https://community.home-assistant.io/t/automation-for-mobile-app-action-dismiss-wont-work/310910)
