### ISSUE TITLE
The actionable notification doesn't return `tag` of the message

### ISSUE THREAD

**Issue by left4taco** [home-assistant/iOS#1666]
**iOS device model, version and app version**

Model Name: iPhone 12 Plug
Software Version: 14.5
App version: 2021.158

**Home Assistant Core Version**

2021.6.5
**Describe the bug**

I'm following the example in [vacation mode with Nodered](https://zachowj.github.io/node-red-contrib-home-assistant-websocket/cookbook/vacation-mode.html#step-2). In the example, an actionable notification was sent to the phone with `tag` in the `data` field to filter out actions sent back by other notification and only handle the `mobile_app_notification_action` event that is meant for this automation.

In the example it looks like the `mobile_app_notification_action` event should come back with the `tag` field, but that's not the case from debugging output.
![image](https://user-images.githubusercontent.com/4816327/122168919-d4eaee00-ce4a-11eb-8a5a-3e959681a137.png)

**To Reproduce**

A minimal reproducible example would be this:

Service call to send the notification
```
service: notify.mobile_app_jojo
data:
  message: "The front door is unlocked!"
  data:
    # replace any existing front_door_lock notifications
    tag: front_door_lock
    actions:
      - action: "ALARM" # The key you are sending for the event
        title: "Sound Alarm" # The button title
      - action: "URI" # Must be set to URI if you plan to use a URI
        title: "Open Url"
```
Event data captured:
```
{
    "event_type": "mobile_app_notification_action",
    "data": {
        "action": "ALARM"
    },
    "origin": "REMOTE",
    "time_fired": "2021-06-16T06:24:23.657627+00:00",
    "context": {
        "id": "03c50fd31e0d99f326de93837980c876",
        "parent_id": null,
        "user_id": "462b3fce20694a84b7619028d2d42b12"
    }
}
```

**Expected behavior**
There should be a `tag` field in the event to tell which notification the reply is from.

**Screenshots**

**Additional context**

**Comment by zacwest** [comment]
I cannot find any documentation that says `tag` will get sent back, nor does it look like the Android app does so. I'm not sure where this came from, can you clarify what you're looking for?

**Comment by t0ny-peng** [comment]
@zacwest Thanks for the reply. I was using the official example from the [`node-red-contrib-home-assistant-websocket`](https://github.com/zachowj/node-red-contrib-home-assistant-websocket) documentation([link](https://zachowj.github.io/node-red-contrib-home-assistant-websocket/cookbook/actionable-notifications-subflow-for-android.html#use-case-1-get-a-notification-when-garage-door-is-left-open-with-ability-to-ignore-the-alert-for-an-amount-of-time)).

In the example, the notify service is called with a tag(thus the message could be updated or so). 
![image](https://user-images.githubusercontent.com/4816327/123895712-44bea580-d92e-11eb-9a5b-32fd2f90ee99.png)

Then when the user click the button, a `mobile_app_notification_action` event is fired. The example flow compares the `tag` field from the event payload with the previously globally set tag to check if the message belong to this flowchart. That's how I get the expectation that the tag will be returned. 
![image](https://user-images.githubusercontent.com/4816327/123895773-6586fb00-d92e-11eb-9200-c90a5b8f2e16.png)

The example was developed by @zachowj. Not sure if you guys know each other😂

**Comment by zacwest** [comment]
I busted out my Android phone, and you're right, it does come through:

```
{
    "event_type": "mobile_app_notification_action",
    "data": {
        "tag": "TEST_TAG",
        "message": "hey",
        "action_1_title": "HEY",
        "action_1_key": "HEY",
        "action": "HEY",
        "device_id": "e30882b6e53743fd"
    },
    "origin": "REMOTE",
    "time_fired": "2021-06-30T03:18:24.422064+00:00",
    "context": {
        "id": "4f548571f045fd4138c40cf3be9fc6da",
        "parent_id": null,
        "user_id": "76ce52a813c44fdf80ee36f926d62328"
    }
}
```

I believe this is an accident, but I'll see if the Android devs want to commit to continuing to support it. If so, I can make the iOS app send tag as well.

**Comment by t0ny-peng** [comment]
@zacwest Thanks for the experiment! It looks like a great feature(and doesn't require too much development work). So I really hope it could be kept

**Comment by richardtjena** [comment]
@zacwest Any news regarding this? 

Would be much appreciated if this was added so that both companion apps delivered the same responses back to Home Assistant.

**Comment by IzeQube** [comment]
Yes, this would be great.

**Comment by danieldotnl** [comment]
I also don't see it in the event_data. How could I react to an actionable notification event without the tag, so without knowing which event it was?

**Comment by macbrook98** [comment]
I also have this issue. I do not see how you can respond to actionable notifications on IOS, using node red, without the tag being returned. This works perfectly with android but no ios support.

IOS:
```
event_type: mobile_app_notification_action
data:
  action: ACKNOWLEDGE
origin: REMOTE
time_fired: "2025-01-22T19:07:41.571344+00:00"
context:
  id: 01JJ7PKHM3NCT8MF5JY2575V2Z
  parent_id: null
  user_id: 700dbd6f6ef44fbf88cb0a0bbcb0c11d
```

Android:
```
event_type: mobile_app_notification_action
data:
  action_2_title: Ignore
  sticky: "true"
  tag: test-tag
  title: title
  webhook_id: e98a2748f5b1a6307c2436de7ac6cd8f7278942c9480dc2e5fd7443144789847
  persistent: "true"
  message: message
  action_1_title: Acknowledge
  action_1_key: ACKNOWLEDGE
  action_2_key: IGNORE
  server_id: "1"
  action: ACKNOWLEDGE
  device_id: f2674999a7a38271
origin: REMOTE
time_fired: "2025-01-22T19:07:09.728393+00:00"
context:
  id: 01JJ7PJJH03V50YEGJDHSZ0M54
  parent_id: null
  user_id: 95a7205e3d3d434b996e0242f44f6608
```

Without returning the tag, it does not appear to be possible to create different actions based on different notification responses and impossible to send `notification_clear` responses either, as they require a tag, as per the docs.

**Comment by danieldotnl** [comment]
I found out that you can actually use the `action` to distinguish different events, like this:
```yaml
trigger: event
event_type: "mobile_app_notification_action"
event_data:
  action: ON_MY_WAY
```

**Comment by macbrook98** [comment]
I might have to give that work-around a go. Although not ideal as it will demand unique actions for every notification type and some sort of script to distinguish tags from these to clear notifications.

Thanks for the idea.

**Comment by bgoncal** [comment]
About updating the notification and clearing it, here is some examples:

Sending first notification:

```
action: notify.mobile_app_bruno_s_iphone
data:
  message: Test
  data:
    tag: tag-1
    actions:
      - action: some-key
        title: Tap here
```

Updating the same notification:

```
action: notify.mobile_app_bruno_s_iphone
data:
  message: Updated test
  data:
    tag: tag-1
    actions:
      - action: some-key
        title: Tap here
```


Clearing this notification:

```
action: notify.mobile_app_bruno_s_iphone
data:
  message: clear_notification
  data:
    tag: tag-1
    actions:
      - action: some-key
        title: Tap here
```

To react to notification actions currently it is only supported to use the action key (e.g. some-key)
