### ISSUE TITLE
hold action on a picture in the ios app brings up the iPhones response to holding a picture: Share, Add, Copy

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/iOS#1698]
**iOS device model, version and app version**

Model Name:  11 pro
Software Version: 14.6
App version:  2021.6 (2021.158) has always been like this see previous [community post](https://community.home-assistant.io/t/tap-action-with-url-doesnt-work-on-app-while-fine-in-desktop-browser/285180)

**Home Assistant Core Version**

2021.7
**Describe the bug**

a hold action on a picture in the ios app brings up the iPhones response to holding a picture: Share, Add, Copy etc, while I would hope it to fire the hold_action defined in the config. Tap action is fine.

A Safari browser on the same iPhone does execute the action.

**To Reproduce**

```
type: entities
entities:
  - type: custom:hui-element
    card_type: entities
    entities: []
    card_mod:
      style: |
        ha-card {
          box-shadow: none;
          margin: -16px -16px 0px -16px;
        }
    header:
      type: picture
      image: /local/weather/weatherbit.png
      tap_action:
        action: url
        url_path: !secret weatherio_api_url
      hold_action:
        action: call-service
        service: homeassistant.reload_config_entry
        service_data:
          entry_id: 79ae77f927714985b1046191c05f2b5c
```

also happening on a regular picture:

```
  - type: custom:hui-element
    card_type: picture
    style: |
      ha-card {
        box-shadow: none;
        margin: -16px -16px 0px -16px;
      }
    image: /local/weather/weatherbit.png
    tap_action:
      action: url
      url_path: !secret weatherio_api_url
    hold_action:
      action: call-service
      service: homeassistant.reload_config_entry
      service_data:
        entry_id: 79ae77f927714985b1046191c05f2b5c
```

**Expected behavior**

execute hold_action. 
**Screenshots**

![20210702_073056000_iOS](https://user-images.githubusercontent.com/33354141/124349239-76659400-dbee-11eb-9f9a-1c979755232d.png)

full card:

<img width="499" alt="Schermafbeelding 2021-07-03 om 11 05 28" src="https://user-images.githubusercontent.com/33354141/124349299-ab71e680-dbee-11eb-8d2f-e8a7ac06ce95.png">

**Additional context**

https://discord.com/channels/330944238910963714/551871772484698112/860422742511190030

**Comment by zacwest** [comment]
Your custom element needs to disable this via `webkit-touch-callout`, see [lovelace version](https://sourcegraph.com/github.com/home-assistant/frontend@df1ca1fd96e3f9b1aa8c2429b396fac82f2cc767/-/blob/src/panels/lovelace/elements/hui-image-element.ts?L66:23).

**Comment by Mariusthvdb** [comment]
nit really sure what you are saying here, im not using any custom elements? or are you referring to the hui-element?

this has nothing to do with that, and can demonstrate that by using this config, using only the core entities card:

```
  - type: entities
    entities: []
    header:
      type: picture
      image: /local/weather/weatherbit.png
      tap_action:
        action: url
        url_path: !secret weatherio_api_url
      hold_action:
        action: call-service
        service: homeassistant.reload_config_entry
        service_data:
          entry_id: 79ae77f927714985b1046191c05f2b5c
```

which behaves exactly the same: tap is alright, hold action presents us with the iOS menu option, and does not call the service as configured.
