### ISSUE TITLE
Allow clear_notification by tag prefix

### ISSUE THREAD

**Issue by nickw444** [home-assistant/iOS#1699]
**Is your feature request related to a problem? Please describe.**

Currently, to use `clear_notification`, you must use the `tag` to create a named identifier for the notification. This however, causes subsequent notifications with the same tag to replace the original due to [Replacing](https://companion.home-assistant.io/docs/notifications/notifications-basic/#replacing)

My use case is that I would like to be able to clear an entire [group](https://companion.home-assistant.io/docs/notifications/notifications-basic/#replacing) of notifications without needing to keep track of the  specific tags given to these and have to keep track of a set of tags to call `clear_notification` on.

Ideally I would dynamically send each notification with 

```yaml
service: notify.mobile_app_<your_device_id_here>
data:
  message: "motion detected whilst away at {{ now() }}"
  data:
    group: "backyard-motion"
    tag: "backyard-motion-detected-{{ now() }}"
```

**Describe the solution you'd like**

Ideally there would be an extension of the `clear_notifications` API:

```yaml
service: notify.mobile_app_<your_device_id_here>
data:
  message: "clear_notifications"
  data:
    tag-prefix: "backyard-motion-detected-"
```

Currently this is handled by this code:

https://github.com/home-assistant/iOS/blob/1db6f3cc6e2826a7464fac139bdad9a55475b9ed/Sources/Shared/Notifications/NotificationCommands/NotificationsCommandManager.swift#L80-L84

which I expect could be extended to call [`getDeliveredNotifications(completionHandler:)`](https://developer.apple.com/documentation/usernotifications/unusernotificationcenter/1649520-getdeliverednotifications) to retrieve the notification and their identifiers, and match them against the prefix and subsequently remove them

**Additional context**

I am not an iOS eng but happy to have a crack at this if there is a chance this would be accepted as a feature!
