### ISSUE TITLE
Received invalid command: mobile_app/push_notification_channel

### ISSUE THREAD

**Issue by gieljnssns** [home-assistant/iOS#1700]
**iOS device model, version and app version**

Model Name: XS
Software Version: 14.6
App version: 2021.7 (2021.200)

**Home Assistant Core Version**

core-2021.7.0b5
**Describe the bug**
Bug also reported at core https://github.com/home-assistant/core/issues/52625
After restarting HA I receive an error from Home Assistant WebSocket API related to mobile_app
And I do not recieven any notifications on my iPhone .
After a reboot of my iPhone those work again.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

```yaml
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:89
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:22:26 (110 occurrences)
Last logged: 11:23:07

[140131635737216] Received invalid command: mobile_app/push_notification_channel
```
