### ISSUE TITLE
GIFs are no longer animated in notifications

### ISSUE THREAD

**Issue by ianwitherow** [home-assistant/iOS#1709]
**iOS device model, version and app version**

Model Name:  iPhone 12 mini
Software Version: 14.6
App version: 2021.7 (2021.202)

**Home Assistant Core Version**
core-2021.7.2

**Describe the bug**
Specifying a GIF as an attachment URL in a notification, when expanding the notification the GIF is no longer animated - just a static image.

**To Reproduce**
To test, I'm sending this notification using the Developer Tools -> Services tab:
```yaml
service: notify.mobile_app_ian_s_iphone
data:
  message: Howdy
  data:
    attachment:
      url: https://static.wixstatic.com/media/4cbe8d_f1ed2800a49649848102c68fc5a66e53~mv2.gif
      content-type: gif
```

**Expected behavior**
When expanding the notification, the GIF should be animated. This was always the case until a few weeks ago (don't remember the exact time it stopped working).

**Screenshots**

**Additional context**

**Comment by zacwest** [comment]
This is a regression, yes. It was caused by moving to our own internal image display when setting attachments (to support retrying and lazy loading), and I neglected to bring in GIF support, which the system supports in its own UI.

You can temporarily work around this by sending…

```yaml
service: notify.xyz
data:
  message: …
  data:
    push:
      # setting category to prevent animated GIF from having issue
      category: DUMMY_CATEGORY_TO_MAKE_ATTACHMENT_ANIMATE
    attachment:
      url: …
```

Important note: you cannot do this and use `actions` in the message payload. You will not need to do this category thing once this is fixed.
