### ISSUE TITLE
Request client to update sensors

### ISSUE THREAD

**Issue by kirbo** [home-assistant/iOS#1828]
Could it be possible to have a possibility for users to request companion to update sensors?
Similar to this:
```yaml
service: notify.mobile_app_<client name here>
data:
  message: "request_location_update"
```
https://github.com/home-assistant/iOS/blob/1db6f3cc6e2826a7464fac139bdad9a55475b9ed/Sources/Shared/Notifications/NotificationCommands/NotificationsCommandManager.swift#L20

Perhaps something like:
```yaml
service: notify.mobile_app_<client name here>
data:
  message: "request_sensors_update"
```
