### ISSUE TITLE
Notification image not loaded on watch outside of network

### ISSUE THREAD

**Issue by golles** [home-assistant/iOS#1838]
**iOS device model, version and app version**

Model Name: iPhoneX (watch: series 5)
Software Version: 14.8 (watch: 7.6.1)
App version: 2021.8 (2021.216)

**Home Assistant Core Version**

2021.9.6

**Describe the bug**
Notification image is not shown on the watch when outside of the house/network. The image is visible on the phone.

**To Reproduce**
Receive a notification when outside that contains an image. Inside (on the network) it works fine.

**Expected behavior**
To always show the image

**Screenshots**
Screenshot on the phone:
![IMG_9294](https://user-images.githubusercontent.com/2211503/133765727-1b78df47-43b0-4c08-927c-7d37791cc8a5.PNG)
On the watch:
![IMG_9295](https://user-images.githubusercontent.com/2211503/133765796-00c22621-ff5b-45e0-83cc-e217daf4d471.jpeg)
![IMG_9296](https://user-images.githubusercontent.com/2211503/133765816-b2b31d84-3490-4118-a2c6-60e08d392100.jpeg)

**Additional context**
This is my configuration, where I add the picture to the entity and the automation:
```yaml
sensor:
  - platform: afvalbeheer
    wastecollector: !secret wastecollector
    resources:
      - restafval
      - gft
      - papier
    postcode: !secret postcode
    streetnumber: !secret streetnumber
    dutch: 1
    disableicons: 1

homeassistant:
  customize:
    sensor.purmerend_restafval:
      friendly_name: Restafval
      entity_picture: /local/afval/purmerend_restafval.jpg
    sensor.purmerend_papier:
      friendly_name: Papier
      entity_picture: /local/afval/purmerend_papier.jpg
    sensor.purmerend_gft:
      friendly_name: GFT
      entity_picture: /local/afval/purmerend_gft.jpg
    
automation:
  - id: afval_notification
    alias: Melding voor afval
    initial_state: on
    mode: single
    variables:
      entity: >-
        {{ 
          states.sensor 
            | selectattr("attributes.Wastecollector", "defined")
            | selectattr("attributes.Days-until", "eq", 1)
            | map(attribute="entity_id")
            | first
            | default("none")
        }}
    trigger:
      platform: time
      at: "19:30:00"
    condition:
      - condition: template
        value_template: >-
          {{ entity != "none" }}
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"
    action:
      - service: notify.sander
        data:
          title: Afval
          message: >-
            Morgen wordt de {{ state_attr(entity, "friendly_name") | upper }} container geleegd.
          data:
            group: afval
            image: >-
              {{ state_attr(entity, "entity_picture") }}

```
All the images are publicly accessible (https://my.ha/local/afval/image.jpg).

**Comment by golles** [comment]
I managed to work around this by forcing images to load externally:
```yaml
automation:
  - id: notification_afval
    alias: "Notificatie: Afval wordt morgen opgehaald"
    mode: single
    variables:
      entity: >-
        {{ 
          states.sensor 
            | selectattr("attributes.Wastecollector", "defined")
            | selectattr("attributes.Days_until", "eq", 1)
            | map(attribute="entity_id")
            | first
            | default("none")
        }}
    trigger:
      platform: time
      at: "19:30:00"
    condition:
      - condition: template
        value_template: >-
          {{ entity != "none" }}
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"
    action:
      - variables:
          external_url: !secret external_url

      - service: notify.sander
        data:
          title: Afval
          message: >-
            Morgen wordt de {{ state_attr(entity, "friendly_name") | upper }} container geleegd.
          data:
            group: afval
            image: >-
              {{ external_url }}{{ state_attr(entity, "entity_picture") }}
            url: /dashboard-buiten/tuin

```
