### ISSUE TITLE
Latest MDI icons missing in iOS app

### ISSUE THREAD

**Issue by TyzzyT** [home-assistant/iOS#1933]
Model Name: iPhone SE
Software Version: iOS 15.1
App version: 2021.11.1

**Home Assistant Core Version**
2021.11.5

**Describe the bug**
In Home Assistant Core 2021.10, the MDI icons were updated to the latest version. I was very happy about this, because now I could change the blinds icon to the curtains icon. As we have curtains in our livingroom, instead of blinds. See also: https://www.home-assistant.io/blog/2021/10/06/release-202110/#updated-material-design-icons
But it looks like I can't use this new icon in iOS actions (both iPhone and Apple Watch), as this action is showing the mdi:ab-testing icon (which is the first icon in the list) Can it be that the MDI icons needs to be updated in the iOS app?

**To Reproduce**
Add the _mdi:curtains_ icon to an iOS action and see the A/B icon showing up instead
```
  - name: Woonkamer gordijnen
    background_color: "#FFBA00"
    label:
      text: "Gord woonkamer"
      color: "#FFFFFF"
    icon:
      icon: curtains
      color: "#FFFFFF"
```

**Expected behavior**
I expect to see the mdi:curtains icon instead of mdi:ab-testing

**Screenshots**
![incoming-BBFF20F1-F5A3-4E3B-A3CD-B51AFF30FC8F](https://user-images.githubusercontent.com/80623729/143675054-4933ca2e-154a-4615-9163-936f41acc473.PNG)
![IMG_1325](https://user-images.githubusercontent.com/80623729/143675055-c6cd164e-d425-482b-aae2-2e7c258dfa42.PNG)
![image](https://user-images.githubusercontent.com/80623729/143675089-eb2f8e87-53b3-4d28-b7e6-37a6d2b6fe78.png)
