### ISSUE TITLE
User defined start lovelace page doesn't work after app restart

### ISSUE THREAD

**Issue by Spirituss** [home-assistant/iOS#1981]
**iOS device model, version and app version**

Model Name: iPhone X
Software Version: 14.5.1
App version: 2021.11.1

**Home Assistant Core Version**

Home Assistant Container
core-2021.10.6

**Describe the bug**
I use non default starting lovelace page, defined in user profile settings:
<img width="638" alt="Снимок экрана 2021-12-07 в 21 30 06" src="https://user-images.githubusercontent.com/47206760/145077433-32423eb3-ae0e-464a-853c-cc52fca0bb92.png">

Almost every time when I start Home Assistant iOS app after some inactive period it starts not from my user defined "Entities" panel, but from HA default page "ui-lovelace.yaml". Thus I have to choose manually the item "Entities" from left bar menu. It looks like that every app restart it "looses" user setting at the first app launch. It often takes place in the launched app after network changes (for example, when you shift with iPhone from LTE to Wi-Fi or vice versa).

I use YAML lovelace mode.

**To Reproduce**

**Expected behavior**
Start from the lovelace page defined in user profile.

**Screenshots**

**Additional context**

```
lovelace:
  mode: yaml
  dashboards:          
    lovelace-entities:
      mode: yaml
      title: Entities
      icon: mdi:palette-swatch
      show_in_sidebar: true
      filename: lovelace-entities.yaml
      require_admin: true
```
