### ISSUE TITLE
macOS Notification content continues playing when notification is dismissed

### ISSUE THREAD

**Issue by zacwest** [home-assistant/iOS#1995]
From a comment in #1210:

>>> Having the same/very similar issue - 

App Version: 2021.266
MacOS Version:  11.6.1
Home Assistant Core Version: core-2021.11.5

When I trigger a notification (with below command) and 'drop down' the notification to show the live RTSP video feed...

```
service: notify.mobile_app_conors_macbook_pro
data:
  message: Someone is at the door
  data:
    entity_id: camera.amcrest_camera
    push:
      sound: "doorbell.wav"

```

... even when I close the notification AND quit the home assistant app (cmd+q) I can still hear the audio from my camera!

_Originally posted by @conorlap in https://github.com/home-assistant/iOS/issues/1210#issuecomment-990225960_
