### ISSUE TITLE
iOS App - Sensor cards all show same plot after locking or switching to running app

### ISSUE THREAD

**Issue by TimCinel** [home-assistant/iOS#2021]
### iOS device model, version and app version

Model Name: iPhone 13 Pro
Software Version: 15.1.1
App version: 2021.12.1

### Home Assistant Core Version

Home Assistant Container
core-2021.11.0

### Describe the bug

Often, the sensor cards for different sensors and different value histories all render the same sensor history plot after locking the phone or switching apps.

### To Reproduce

1. View a dashboard showing multiple sensor cards
2. Lock and unlock the phone repeatedly or switch between Home Assistant and other apps repeatedly
3. The sensor cards all show the same plot.

Hard refresh, by pulling down the page, fixes the problem until the next lock or app switch.

See screenshots.

### Expected behavior

When viewing a dashboard with multiple sensor cards, each sensor card's plot should represent the history for its sensor.

### Screenshots

https://user-images.githubusercontent.com/177173/147045596-f031d35a-815a-4157-9718-713af8250ec1.mov

### Additional context

Lovelace config:

```
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.envoy_current_energy_production
                graph: line
                hours_to_show: 12
                icon: mdi:arrow-up
                unit: W
                name: Production
              - type: sensor
                entity: sensor.envoy_current_energy_consumption
                graph: line
                hours_to_show: 12
                icon: mdi:arrow-down
                unit: W
                name: Consumption
          - type: glance
            entities:
              - entity: sensor.envoy_today_s_energy_production
              - entity: sensor.envoy_today_s_energy_consumption
            show_icon: false
            show_name: false
          - type: sensor
            entity: sensor.current_energy_cost
            graph: line
            hours_to_show: 12
            icon: mdi:currency-usd
            unit: AUD / hour
            name: Real Time Energy Cost
            detail: 2
```
