### ISSUE TITLE
The dial pop up does not show when multiple # are used in the phone number

### ISSUE THREAD

**Issue by Skons** [home-assistant/iOS#2040]
**iOS device model, version and app version**

Model Name: iPhone 11
Software Version: 15.2
App version: 2021.12.1 (2021.327)

**Home Assistant Core Version**
2021.12.3

**Describe the bug**
Unable to send url: 'tel:#31#'. It seems that having 2 # in a phone number does not trigger the Companion app to offer the dial menu. If only one # is used, the dial popup will show

**To Reproduce**
```
service: notify.mobile_app
data:
  message: test
  title: test
  data:
    url: 'tel:#31#00000000'
```

**Expected behavior**
A dial popup with the number to dial
