### ISSUE TITLE
clear_notification is not working on MacOS

### ISSUE THREAD

**Issue by conorlap** [home-assistant/iOS#2042]
**Device model, version and app version**

Model Name: MacBook Pro (Retina, 15-inch, Late 2013)
macOS Version: 11.6.2
App Version: 2021.12 (2021.322)
Safari Version: Version 15.2 (16612.3.6.1.8, 16612)

**Home Assistant Core Version**
core-2021.12.9

**Describe the bug**
clear_notification is not working as expected for MacOS

**To Reproduce**
```
service: notify.mobile_app_conors_macbook_pro
data:
  message: Someone is at the door
  data:
    tag: "doorbellpress"
    image: /local/snapshots/amcrest_snapshot.jpg
    push:
      sound: 
        name: doorbell.wav


service: notify.mobile_app_conors_macbook_pro
data:
  message: "clear_notification"
  data:
    tag: "doorbellpress"
```

**Expected behavior**

The notification should clear once the clear_notification is sent.
