### ISSUE TITLE
Iframe / Webpage-Card issue

### ISSUE THREAD

**Issue by YvesZH** [home-assistant/iOS#2102]
Model Name:  IPhone 13pro
Software Version: ios15
App version:  2022.3

 
**Home Assistant Core Version**
2022.3.5

When I use the official lovelace card [iframe/webpage](https://www.home-assistant.io/lovelace/iframe/) in the companion app for ios, only the following content is visible (and do nothing else than show the loading screen):
![5807DCD7-7242-4F3D-8445-884D6ACA4EF9](https://user-images.githubusercontent.com/64573990/159097735-6e3daac6-173e-46bd-8cf3-e1d168a9a266.jpeg)

The following is configured in lovelace:
```
  - type: iframe
    url: /media-browser/media_player.buro/xxx
    aspect_ratio: 110%
```

With the same configuration it works in the desktop browser and in all ios browsers (safari & co) :
![B79328AB-243A-4A67-AD84-E0F60B3D494A](https://user-images.githubusercontent.com/64573990/159097797-78647d75-c6a7-4988-8229-abd90ac5aa44.jpeg)

I tried it with different url (internal/external).  Unfortunately the same effect.  The same error is also shown with this lovelace configuration (only always in the ios companion app):
```
  - type: custom:button-card
    show_name: false
    icon: mdi:play-box-multiple-outline
    tap_action:
      haptic: heavy
      action: fire-dom-event
      browser_mod:
        command: popup
        title: Media Browser
        hide_header: false
        large: false
        card:
          type: iframe
          url: /media-browser/media_player.buro/xxx
          aspect_ratio: 100%
```

'Crossside tracking' in the ios systemsetting for the companion app is enabled.
