### ISSUE TITLE
Unable to escape URI image view from actionable notification

### ISSUE THREAD

**Issue by brahmafear** [home-assistant/iOS#2107]
**iOS device model, version and app version**

Model Name: iPhoneSE (2020)
Software Version: 15.3.1
App version: 2022.3

**Home Assistant Core Version**

2022.3.8

**Describe the bug**
Actionable notification with action to load photo puts app in a state that is impossible to return to main screen.  Only image and "gear" icon shown with no ability to return to app home screen.  Force quitting app and restarting returns app to same image viewing screen.  

**To Reproduce**
Load URI of image in actionable notification.  

**Expected behavior**
Screen element allowing return to app home screen.  

**Screenshots**

![IMG_AB36F6D98EC7-1](https://user-images.githubusercontent.com/5796940/162209141-f64204e6-5f66-46ff-8beb-bd0335780d10.jpeg)

**Additional context**

Code used for actionable notification:
```
    action:
      - service: notify.mobile_app_dwmip
        data:
          message: 'A {{trigger.payload_json["after"]["label"]}} was detected at {{trigger.payload_json["after"]["camera"]}}.'
          data:
            image: >-
              https://<redacted>:8123/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg
            # video: >-
            #   https://<redacted>:8123/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/clip.mp4
            tag: '{{trigger.payload_json["after"]["id"]}}'
            when: '{{trigger.payload_json["after"]["start_time"]|int}}'
            entity_id: camera.{{trigger.payload_json["after"]["camera"]}}
            actions:
              - action: "URI"
                title: "View Image"
                uri: https://<redacted>:8123/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg
              - action: "URI"
                title: "Open Clip"
                uri: https://<redacted>:8123/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/clip.mp4
    mode: single
```
