### ISSUE TITLE
Data in textInputButtonTitle and textInputPlaceholder Does Not Appear in Actionable Notification

### ISSUE THREAD

**Issue by greg-nyc** [home-assistant/iOS#2167]
**iOS device model, version and app version**

Model Name: iPhone 11 Pro Max
Software Version: 15.6
App version: 2022.3 (2022.358)

**Home Assistant Core Version**

2022.7.7

**Describe the bug**
Data in `textInputButtonTitle` and `textInputPlaceholder` does not appear in notification.

**To Reproduce**
```
script:
  actionable_notifications:
    alias: AN Testing
    icon: mdi:cellphone-message
    description: Testing AN
    mode: queued
    sequence:
      - service: notify.mobile_app_phone
        data:
          message: "AN Testing"
          data:
            actions:
              - action: "REPLY"
                title: "Title Text"
                textInputButtonTitle: "Button Title Text Input"
                textInputPlaceholder: "Placeholder Text"
```

When running this script, the actionable notification fails to display the text in `textInputButtonTitle` and `textInputPlaceholder`

**Expected behavior**

Per the documentation, the data stored in these keys should appear in the notification.

**Screenshots**

![IMG_7229](https://user-images.githubusercontent.com/58618524/182274316-1b41ba29-c777-4ee0-9ce2-cc4429b7e8e4.PNG)
![IMG_7230](https://user-images.githubusercontent.com/58618524/182274327-a8150d36-4f67-4583-834f-359b5745f204.PNG)

**Additional context**

This is the first time I've attempted to use these keys, so I don't know when this bug first appeared.
