### ISSUE TITLE
watchOS Actionable Notification Text Input Fails to Fire Event

### ISSUE THREAD

**Issue by greg-nyc** [home-assistant/iOS#2168]
**iOS device model, version and app version**

Model Name: Apple Watch Series 6
Software Version: 8.6 (19T572)
App version: 2022.3 (2022.358)

**Home Assistant Core Version**
2022.7.7

**Describe the bug**
In response to an actionable notification that appears on an Apple Watch, actions that solicit text input do not generate activity on the mobile_app_notification_action or ios.notification_action_fired event busses. For example, when selecting the Title Text button the automation below generates, the user is prompted to enter text. After text has been entered, pressing "Send" clears the notification, but no mobile_app_notification_action or ios.notification_action_fired events are fired.

I confirmed that if a non-text input action is selected on the watch, an event is created as expected.

**To Reproduce**
```
script:
  actionable_notifications:
    alias: AN Testing
    icon: mdi:cellphone-message
    description: Testing AN
    mode: queued
    sequence:
      - service: notify.mobile_app_phone
        data:
          message: "AN Testing"
          data:
            actions:
              - action: "REPLY"
                title: "Title Text"
                textInputButtonTitle: "Button Title Text Input"
                textInputPlaceholder: "Placeholder Text"
```

Run the script. Select the Title Text option, click on the Reply that appears, enter text in the text display, then press Send.

**Expected behavior**
An event should be created and the reply text entered by the user should appear in the data in the event. For example, this is what we should be seeing when the event is fired:

```
...
    "data": {
        "action": "REPLY",
        "reply_text": "Testing"
...
```

**Screenshots**

**Additional context**

This is the first time I've attempted to use the `textInput` functionality in the Companion app's actionable notifications, so I don't know when this bug first appeared.
