### ISSUE TITLE
History-graph wont show graph, only popup

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/iOS#2170]
**iOS device model, version and app version**

Model Name: 13Pro
Software Version: 15.6
App version:  2022.358

**Home Assistant Core Version**

<img width="433" alt="Schermafbeelding 2022-08-06 om 12 43 05" src="https://user-images.githubusercontent.com/33354141/183245574-62469873-9d89-40fe-9a6d-3b6a1b353cd2.png">

**Describe the bug**

as title, one knows he graph is there, because of the popups that do show when touching/hovering

**To Reproduce**
```
    - type: entities
      title: History include all domains
      entities:

        - type: custom:auto-entities
          card:
            type: history-graph
            hours_to_show: 12
          filter:
            include:
              - domain: "*"
```

shows fine on desktop, but nothing on Mobile
**Expected behavior**

**Screenshots**

**Additional context**
