### ISSUE TITLE
clear_notification only working with Local Push

### ISSUE THREAD

**Issue by marce14-git** [home-assistant/iOS#2184]
**iOS device model, version and app version**

Model Name:  iPhone 12 Pro 
Software Version: 15.6
App version: 2022.3(2022.358

**Home Assistant Core Version**
8.4

**Describe the bug**
clear_notification for iOS Notifications is only working when Local Push is active 

**To Reproduce**

1. Send notification to iOS
```
service: notify.mobile_app_iphone_12_pro
data:
  message: "test"
  data:
    tag: "test"

```
2. Send clear notification
```
service: notify.mobile_app_iphone_12_pro
data:
  message: "clear_notification"
  data:
    tag: "test"
```

3. First Notification only gets cleared when Local Push is activated

**Expected behavior**
clear_notification should work regardless if you have local push active or deactivated
