### ISSUE TITLE
iOS 16: `volume` for critical notification sounds not working anymore

### ISSUE THREAD

**Issue by robertklep** [home-assistant/iOS#2204]
**iOS device model, version and app version**

Model Name: iPhone 12 mini
Software Version: iOS 16.0
App version: 2022.8 (2022.387)

**Home Assistant Core Version**

Home Assistant Core 2022.8.6

**Describe the bug**
The `volume` property for critical notification sounds doesn't work anymore. This might be an iOS 16 bug, see "Additional context" below.

**To Reproduce**
Send a critical notification at 10% level:
```
service: notify.mobile_app_<your_device_id>
data:
  message: "Hello World!"
  data:
    push:
      sound:
        name: "default"
        critical: 1
        volume: 0.1
```

**Expected behavior**
Critical notification sounds should be played at the volume specified in the push notification.

**Additional context**

When the notification is received, the volume bar on the left side of the screen is shown and the volume seems to get set to what the `volume` property is set to. However, the sound itself gets played at a different volume regardless.

If I open an app that plays music (SoundCloud in my case), the music is played at proper system volume. After that, critical notification sounds are _also_ played at that volume, hence my suspicion it might be an iOS 16 bug.
