### ISSUE TITLE
Add an option to restrict synced actions to specific users in the YAML configuration

### ISSUE THREAD

**Issue by mjodko** [home-assistant/iOS#2208]
Managing actions in the mobile app is a rather tedious task, especially if a larger number of users is involved.

The synced actions feature already addresses that, but I believe actions can be (and definitely are in my case) very user-specific. And since there is no way to simply toggle synced actions on and off on a per-user basis (which is the case for scenes), I propose extending the existing YAML syntax to allow whitelisting/blacklisting users for each action.

Example:
```yaml
ios:
  actions:
    - name: Lights in room 1
      background_color: "#223377"
      label:
        text: "Room 1"
        color: "#ffffff"
      icon:
        icon: lightbulb-on
        color: "#ffffff"
      users:
        - user1
        - user2
    - name: Lights in room 2
      background_color: "#332277"
      label:
        text: "Room 2"
        color: "#ffffff"
      icon:
        icon: lightbulb-on
        color: "#ffffff"
      exclude_users:
        - user2
        - user3
```
where the `users` and `exclude_users` clauses are optional and mutually exclusive.
