### ISSUE TITLE
Action name instead of label being used

### ISSUE THREAD

**Issue by alphasixtyfive** [home-assistant/iOS#2255]
**Device model, version and app version**

Model Name: MacBook Pro 13Inch 2018
macOS Version: Ventura 13.0.1
App Version: 2022.10.1 (2022.424)
Safari Version: 16.1

**Home Assistant Core Version**
2022.11.2

**Describe the bug**

MacOS app displays action name instead of label within the app while label is correctly used on iPhone and Apple Watch.

**To Reproduce**

```
ios:
  actions:
    - name: LIGHTS_OFF
      background_color: "#607D8B"
      label:
        text: "Lights off"
        color: "#ffffff"
      icon:
        icon: lightbulb-group-off
        color: "#ffffff"

    - name: FRONT_GATE_TOGGLE
      background_color: "#3949AB"
      label:
        text: "Front gate"
        color: "#ffffff"
      icon:
        icon: gate
        color: "#ffffff"

    - name: REAR_GATE_TOGGLE
      background_color: "#388E3C"
      label:
        text: "Front gate"
        color: "#ffffff"
      icon:
        icon: gate
        color: "#ffffff"
```

**Expected behavior**

**Screenshots**

<img width="464" alt="Screenshot 2022-11-15 at 15 32 44" src="https://user-images.githubusercontent.com/55880648/201961392-854e6d23-02dc-4366-8e15-713c67d746ed.png">
