### ISSUE TITLE
entityId URL in notifications doesn't work

### ISSUE THREAD

**Issue by llamafilm** [home-assistant/iOS#2260]
**iOS device model, version and app version**
Model Name: iPhone 12 Pro
Software Version: iOS 16.1.1
App version: 2022.10.1 (2022.424)

**Home Assistant Core Version**
 2022.11.5

**Describe the bug**
Sending a notification with entityId style URL opens the app to the default page instead of the More Info page of the specified entity.

**To Reproduce**
```yaml
service: notify.mobile_app_pro_llama
data:
  message: test message
  data:
    url: entityId:sun.sun
```

**Additional context**
This is the first time I've ever tried to use this style of notification, so perhaps I'm doing something wrong.  I got the syntax from documentation: https://companion.home-assistant.io/docs/notifications/notifications-basic#opening-a-url

The log file shows this:
```
2022-12-04 22:22:16.351 [Info] [main] [NotificationManager.swift:250] userNotificationCenter(_:didReceive:withCompletionHandler:) > launching URL entityId:sun.sun
```
