### ISSUE TITLE
views with cameras won't release and 'break' iPhone app (not Mac OS App)

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/iOS#2286]
**iOS device model, version and app version**

Model Name: iPhone 13 Pro
Software Version: 16.2
App version: 2022.10.1(2022.424)

**Home Assistant Core Version**

2023.1.5
**Describe the bug**

view with (Unifi PoE and Wifi) camera cards grinding the app, and no way to get it back other than restarting the iPhone ... https://community.home-assistant.io/t/view-with-cameras-completely-grinds-the-ios-app/517489

initially the view seems to load fine, and I can switch between views inside that (dedicated Camera) dashboard. However, they wont load new info (turning on an off camera wont load) and navigating to other dashboards is practically impossible. They simply wont load, or maybe, maybe after waiting for an enormous amount of time (minutes)...
pulling down the app view to refresh shows the circling icon for ever.

Swiping up the app and reopening does not help, it simply returns to the cam view in the same dead/hung state.
Only restarting the iPhone helps, and gives me my app back again.

Also, clicking a camera view does Not load the more-info, it only reveals an empty card.

**To Reproduce**

a plain view config like:
```
cards:

  - <<: &camera
      type: picture-entity
      show_state: true
      show_name: true
      camera_view: live
    entity: camera.oprit
  - <<: *camera
    entity: camera.poort
  - <<: *camera
    entity: camera.voordeur
  - <<: *camera
    entity: camera.terras
```

fwiw, Ive also tested the full card views with
```
    entity: camera.[[entity]]
    size: 100%
    type: custom:button-card
    show_live_stream: true
    show_name: false
    styles:
      card:
        - padding: 0px
```

to check if its the picture-entity card, but that has no significant difference. The view is identical and the effect on mobile is just as destructive.

**Expected behavior**
be able to navigate away from the camera view without issue.

**Screenshots**

**Additional context**

maybe related? https://github.com/home-assistant/frontend/issues/14136

when the issue was noticed, I did Not have default_config: in configuration.yaml, and also did Not have `[stream:](https://www.home-assistant.io/integrations/stream/)` enabled in my config.
After some chatter in Discord I added it to my config, and that apparently helped to show the camera cards on more-info, they now load ok.

```
stream:
  ll_hls: true
  part_duration: 0.75
  segment_duration: 6
```
copied from the documentation, but I do not understand what this does, so would not know how to experiment with these settings.

It does not help the grinding of the app though, that is still completely unusable.

Hardware is a Mele mini pc with enormous amounts of memory. Cameras are served from a UDM pro

Dekstop website browsing does Not have the issue, nor does the iOS Mac app, that is blazingly fast.

The linked frontend issue above is still unanswered, and tbh, it does not really cause issues elsewhere, it was by accident I noticed that. Yet, could it be causing this issue on the iPhone?
