### ISSUE TITLE
HomeKit Remote App does not fire any Home Assistant Events

### ISSUE THREAD

**Issue by daredoes** [home-assistant/iOS#2317]
Model Name: Apple Watch
Software Version: Latest OS
App version: Unknown

**Home Assistant Core Version**
2023.3

**Describe the bug**
The Remote app on Apple Watch does not fire any events in Home Assistant, and has no documentation on it, so TVs added to Apple Home through Home Assistant cannot be controlled via Apple Watch

**To Reproduce**
Add a Universal Media Player as recommended in the Home Assistant HomeKit docs to control a TV.
Add the TV to Apple Home via Home Assistant
Open the Remote app on Apple Watch to control the added TV
Click the remote touchpad/rotate the dial with no effect/events

**Expected behavior**
Events are fired in Home Assistant so each tap/wheel scroll can be controlled via Automations

**Additional context**
Originally filed bug with more effort/detail https://github.com/home-assistant/home-assistant.io/issues/25610

**Comment by Morcains** [comment]
Just tried to google this very issue and can confirm what @daredoes is saying. I have the following setup for my TV:

```yaml
homekit:
  - name: TV Bridge
    port: 55001
    mode: accessory
    filter:
      include_entities:
        - media_player.living_room_tv_3
    entity_config:
      media_player.living_room_tv_3:
        feature_list:
          - feature: on_off
          - feature: play_pause
          - feature: play_stop
          - feature: toggle_mute
```

When using my iPhone as a remote the events are fired as expected, but trying the same thing from my watch seconds later has no effect at all.
