### ISSUE TITLE
ibeacon is not working with iOS companion app

### ISSUE THREAD

**Issue by jokerigno** [home-assistant/iOS#2380]
**iOS device model, version and app version**

Model Name: iphone 12 mini
Software Version: 16.5.1 (c)
App version: 2023.4 (2023.460)

**Home Assistant Core Version**

 Home Assistant 2023.7.3 Supervisor 2023.07.1 Operating System 10.3 Frontend 20230705.1 - latest 
**Describe the bug**
I created a zone with the details of a ibeacon in order to save car location.

```
zone:
  - name: Herbie
    latitude: 1.2345
    longitude: 6.7890
    radius: 0.3
    icon: mdi:car
    passive: true
```

```
homeassistant:
  customize:
    zone.herbie:
      track_ios: true
      beacon:
        uuid: 7B8B08E8-xxxx-xxxx-xxxx-0A388903DE6F
        major: 1
        minor: 1
    device_tracker.herbie_herbie:
      entity_picture: /local/herbie.jpg`

```

**To Reproduce**

**Expected behavior**

I was expecting that proximity of the beacon will trigger location (as it does with my wife's android phone. But it does not.
NB: I installed owntracks, created a region with same UUID major and minor and when the app is in background my phone update car position (update ibeacon in my car).

**Screenshots**

**Additional context**
