### ISSUE TITLE
Add Sensor for Sleep Mode/Focus

### ISSUE THREAD

**Issue by scolby33** [home-assistant/iOS#2399]
It would be useful to me to determine when I have entered or exited the Sleep Focus specifically. From a glance through the `INFocusStatus` documentation, I don't think this is possible to do with the current focus sensor (originally, I expected that there would be an attribute on that sensor with the name of the selected focus, but it seems like Apple won't let you do that).

It might be possible however to get "is currently in sleep mode" from the HealthKit API. Perhaps an [Observer Query](https://developer.apple.com/documentation/healthkit/hkobserverquery/executing_observer_queries) would be the way to go.

Thank you for considering this request!

**Comment by cpvbruno** [comment]
A quick workaround would be to use the iOS shortcuts app and create an automation that hits a HA webhook and updates the state.

**Comment by scolby33** [comment]
That's a great idea! Here's the breakdown of what I did for this:

## Shortcuts Automation

**When:** When Bedtime starts

**Do:**

1. Get Wi-Fi network's Network Name
2. If Network Details is not `My Home Network`: Stop this shortcut
3. Dictionary: `{"focus_action": "sleep"}`
4. Fire `shortcut_event` with data

## HA Side
In `configuration.yaml`:
```yaml
template:
  - trigger:
      - platform: event
        event_type: "shortcut_event"
        event_data:
          focus_activated: "sleep"
        id: "sleep_on"
      - platform: state
        entity_id:
          - binary_sensor.iphone_focus
        to: "off"
        id: "focus_off"
      - platform: state
        entity_id:
          - binary_sensor.scott_sleep_focus
        to: "off"
        id: "self_off"
    unique_id: a7b4e799-c1b5-4417-ba94-3968e9f42329
    binary_sensor:
      - name: Scott Sleep Focus
        state: '{{ trigger.id == "sleep_on" }}'
        icon: '{{ (trigger.id == "sleep_on") | iif("mdi:bed", "mdi:bed-empty") }}'
        unique_id: 17b611fe-5ce0-4a72-b897-5201aa229b02
```

This could misfire if you go directly from Sleep focus to another non-sleep focus, but that's not something I do, so this works for me.
