### ISSUE TITLE
iOS Companion App Not Executing Query String in URI

### ISSUE THREAD

**Issue by kirsch33** [home-assistant/iOS#2403]
**iOS device model, version and app version**

Model Name: iPhone 13 
Software Version:  iOS 16.6
App version: HA companion app version 2023.460

**Home Assistant Core Version**

Home Assistant server version 2023.8.4, supervisor 2023.08.1, operating system 10.5

**Describe the bug**

Using a script in home assistant, it is possible to open a Safari link directly into the HA app if the URI provided is a lovelace subdirectory. for example, this automation will open my Frigate camera dashboard within HA (correctly) when executed
```yaml
script:
  send_dynamic_notification:
    sequence:
      - service: notify.mobile_app_austins_iphone
        data:
          message: "{{ message }}"
          data:
            tag: "{{ notifTag }}"
            group: "{{ group }}"
            image: "{{ null }}"
            video: "{{ null }}"
            attachment:
              url: "{{ image }}"
            push:
              interruption-level: active
            actions:
              - action: URI
                title: "View Clip In Browser"
                uri: "{{ video }}"
                destructive: false
              - action: URI
                title: "View Live"
                uri: "/lovelace/frigate"
                destructive: false
    mode: single
```

However, the Frigate card (https://github.com/dermotduffy/frigate-hass-card) is capabale of passing actions thru the URI as well via query strings. however, HA companion app does not recognize or utilize any provided query strings.

in the above example, if I change this line:

```
uri: "/lovelace/frigate"
```

to

```
uri: "/lovelace/frigate?frigate-card-action:live&frigate-card-action:camera_select={{ camera }}"
```

this should open the specific requested camera, but does not. 

I have tested that this works fine on the iOS Safari app itself, but just not as intended with the HA companion app itself.

**Additional context**
For additional context see my post in this issue over on the frigate-hass-card repo 
https://github.com/dermotduffy/frigate-hass-card/issues/1253#issuecomment-1696566488
