### ISSUE TITLE
2023.7 no longer showing media (image/video) in notifications

### ISSUE THREAD

**Issue by cmsimike** [home-assistant/iOS#2428]
**iOS device model, version and app version**

Model Name: iPhone 11 Max Pro
Software Version: 17.0.3
App version: 2023.7

**Home Assistant Core Version**
2023.9.3

**Describe the bug**
Notifications no longer showing images/videos that previously worked before upgrading to the app version 2023.7

**To Reproduce**

Send a notification to the iOS app and include a video or image:
```yaml
id: "exampleID"
alias: notify_if_cat_detected_anywhere
description: "cat_notify_anywhere"
trigger:
  - platform: mqtt
    topic: frigate/events
    payload: new
    value_template: "{{ value_json.type }}"
condition:
  - "{{ 'cat' in trigger.payload_json['after']['label'] }}"
action:
  - service: notify.mobile_app_example_s_iphone
    data:
      message: 'A {{trigger.payload_json["after"]["label"]}} was detected.'
      data:
        image: >-
          https://home.example.com/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg
        tag: '{{trigger.payload_json["after"]["id"]}}'
        when: '{{trigger.payload_json["after"]["start_time"]|int}}'
        entity_id: camera.{{trigger.payload_json["after"]["camera"]}}
  - service: notify.mobile_app_example
    data:
      message: 'A {{trigger.payload_json["after"]["label"]}} was detected.'
      data:
        image: >-
          https://home.example.com/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg
        tag: '{{trigger.payload_json["after"]["id"]}}'
        when: '{{trigger.payload_json["after"]["start_time"]|int}}'
        entity_id: camera.{{trigger.payload_json["after"]["camera"]}}
  - service: notify.matrix_notify
    data:
      message: 'A {{trigger.payload_json["after"]["label"]}} was detected by {{trigger.payload_json["after"]["camera"]}}. https://home.example.com/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg with a score of {{trigger.payload_json["after"]["score"]}}'
mode: single
```

**Expected behavior**
The image should show

**Additional context**
This automation worked fine before upgrading my iOS app to 2023.7

**Comment by N3rdix** [comment]
Cannot confirm, for me it is still working on an old iPad Air 2. Showing the camera live stream is still working as before.
My working example:
```
service: notify.mobile_app_ipad
data:
  message: "Just a test"
  data:
    entity_id: camera.eingangsbereich
  title: Es hat geklingelt!
```

Is the image completely gone or does is just show an error similar to this?
![image](https://github.com/home-assistant/iOS/assets/70015952/50288cb8-b8e1-4046-a617-694eea85442d)
