### ISSUE TITLE
Zone GPS coordinates and iBeacon do not co-exist

### ISSUE THREAD

**Issue by devanl** [home-assistant/iOS#243]
**Home Assistant release with the issue:**
0.84.6

**Last working Home Assistant release (if known):**
N/A

**Operating environment (Hass.io/Docker/Windows/etc.):**
Raspbian

**Component/platform:**
iOS Location Tracking

**Description of problem:**
Zone defined with GPS coordinates and iBeacon to allow support in yard (GPS) with quick detection of location on arrival (iBeacon).  The iOS device will go in and out of zone, presumably as beacon goes in and out of range despite GPS reporting location within zone.

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml
zone 5:
  name: Home
  latitude: xx.xx
  longitude: -xx.xxx
  radius: 300
  beacon:
    uuid: 74278bda-b644-4520-8f0c-720eaf059935
    major: 65504
    minor: 65505

ios:

automation:
- action:
  - data_template:
      message: '{{ trigger.from_state.name }} has changed from  {{ trigger.from_state.state }} to {{ trigger.to_state.state }}'
      title: Device Tracker
    service: notify.ios_devans_iphone
  alias: Zone Change
  condition:
    condition: template
    value_template: '{{ trigger.from_state.state != trigger.to_state.state }}'
  id: '1510437649544'
  trigger:
  - entity_id: device_tracker.devans_iphone
    platform: state

```

**Traceback (if applicable):**
```

```

**Additional information:**
Automation is used to identify state updates.
