### ISSUE TITLE
Logbook card: "Uncaught error from WebKit 605.1.15 on iOS 16.7.2 Script error. null @:0:0" on refresh

### ISSUE THREAD

**Issue by dolodobendan** [home-assistant/iOS#2439]
**iOS device model, version and app version**
--

Model Name: iPhone 8
Software Version: 16.7.2
App version: 2023.7

**Home Assistant Core Version**
--
Core: 2023.11.0
Supervisor: 2023.10.1
Operating System: 11.1
Frontend: 20231030.1

**Describe the bug**
--
Refreshing a view in the iOS app with a logbook card with around 20 entries results in this error:

```
Logger: frontend.js.latest.202310301
Source: components/system_log/__init__.py:300
First occurred: 20:01:31 (1 occurrences)
Last logged: 20:01:31

Uncaught error from WebKit 605.1.15 on iOS 16.7.2 Script error. null @:0:0
```

**To Reproduce**
--

1. Have a view with a logbook card*
2. Have 20+ entries in that logbook card
3. Refresh the respective view in the iOS app

I created this one here: input_boolean.log_test and toggled it in the web UI, thus creating entries. After each toggle I refreshed the view on my phone and checked the logs whether the error occurred. At around 20 entries it started to occur.

*) Like this one:

```
  - title: TEST
    path: TEST
    badges: []
    cards:
      - type: logbook
        entities:
          - input_boolean.log_test
      - type: tile
        entity: input_boolean.log_test
```

**Expected behavior**
The view refreshes without an uncaught error from WebKit.
