### ISSUE TITLE
Predefined Actions Don't Work Anymore

### ISSUE THREAD

**Issue by meironke** [home-assistant/iOS#2440]
**iOS device model, version and app version**

Model Name: iPhone 13 pro (MLVE3ZD/A)
Software Version: iOS 17.0.3
App version: 2023.7 2323.471

**Home Assistant Core Version**
2023.7

**Describe the bug**
The predefined actions within the `configuration.yaml` are no more available (since ~2 months). First I thought it would be a iOS17 bug, but within my iPad10 it is also not availble with iOS16.x.

**To Reproduce**
1. removed all iOS related configuration within the `configuration.yaml`
2. added the code block from the description page (see below)
3. restarted Home Assistant
4. de-installed the iOS app(s) on 2 iPads and 2 iPhones (each iOS16 and/or iOS17)
5. re-installed the apps
6. opened companion app, settings, companion app, actions
**No predefined actions there.**

Added this config to the `configuration.yaml` (copy pasted from [here](https://companion.home-assistant.io/docs/core/actions/#creating-actions-in-home-assistant))
```
ios:
  actions:
    - name: Fred
      background_color: "#000000"
      label:
        text: "Hello, World"
        color: "#ff0000"
      icon:
        icon: earth
        color: "#ffffff"
```

**Expected behavior**
Predefined actions should appear and work.

**Screenshots**
![image](https://github.com/home-assistant/iOS/assets/56265223/caa00a0e-d2ee-4346-aa65-88c84eab6420)

**Additional context**

- I have tried it with many configurations, even those that used to work couple of weeks ago. No chance to get the prefedined actions working again.
- I can define manual actions, they will persist.
- Standard _scenes_ that have been defined within HA are available.
