### ISSUE TITLE
Notification Actions don't work on WatchOS 10

### ISSUE THREAD

**Issue by Gloomyeye** [home-assistant/iOS#2454]
**iOS device model, version and app version**

Model Name: Apple Watch Series 9
Software Version: 10.1.1
App version: 2023.7 (2023.471)

**Home Assistant Core Version**
Docker Environment with 2023.11.2

**Describe the bug**

If I send a notification to my iPhone / apple watch, I can not see the notification actions on my watch. Only a message like "Notifications will be loaded" are shown on the watch display, but nothing happens. The iPhone shows the correct buttons for the notification actions. This behaviour occured with the newest watchOS version 10.x.

**To Reproduce**

Send a notification to iphone/apple watch with defined action. For example with the following service call:

```
  service: mobile_app_iphone
  service_data:
    title: Mülltonne zurückstellen
    message: Wurde die Mülltonne zurückgestellt?
    data:
      url: /lovelace/waste
      group: glo-notify-trash
      tag: glo-notify-trash-back
      actions:
        - action: TRASH_NOTIFY_02_DENY_01HFP9NX30FD6K6YR5Y5MD3YS8
          title: Deaktivieren
          activationMode: background
          authenticationRequired: false
          destructive: true
```

**Expected behavior**

The notification actions are loaded and shown for usage on the Apple Watch (like on the iPhone).

**Screenshots**

**Additional context**
