### ISSUE TITLE
iPad OS - HA app closes when opening URL

### ISSUE THREAD

**Issue by Jkraghify** [home-assistant/iOS#2485]
Model Name: iPad Pro (11-inch)
Software Version: iPad OS 17.2
App version: 2023.7 (2023.471)

**Home Assistant Core Version**
2023.12.3

**Describe the bug**
When I try to open a link to anything in home assistant through iPadOS (tap on notification with URL, tap on Home Assistant Notification Settings in Settings > Home Assistant > Notifications), the home assistant companion app opens the link and immediately closes.

**To Reproduce**
Send a notification to an iPad:

```
service: notify.mobile_app_herot
data:
  message: message
  data:
    url: /lovelace/default_view
```

Tap on the notification.
HA closes

**Expected behavior**
This should open the HA app to the default dashboard view, but instead the app closes.
