### ISSUE TITLE
Notifications with image attachments broken

### ISSUE THREAD

**Issue by jwfox5150** [home-assistant/iOS#2556]
**iOS device model, version and app version**
Model Name: iPhone 14 Pro Max
Software Version: iOS 17.3
App Version: 2024.1

**Home Assistant Core Version**
2024.1.3, 2024.1.5

**Describe the bug**
Following updating the companion app version to 2024.1, notifications that are supposed to include an attached image no longer contain the image, and actionable buttons no longer load (remains "Loading Actions..." upon expanding the notification).

**To Reproduce**
Example automation service call:
```
service: notify.mobile_app_iphone
data:
  message: Vehicle detected in driveway
  title: Vehicle • Driveway
  data:
    attachment:
      url: https://link.to.HA.com/local/driveway.jpg
    actions:
      - action: MUTE_15_ALL
        title: Mute cams 15 min.
      - action: MUTE_120_ALL
        title: Mute cams 2 hours
```

**Expected behavior**
Notification comes through with image attached and actionable buttons visible.

**Additional context**
Notifications on the Apple Watch function as expected - both with image attachment and actionable buttons.

**Comment by bgoncal** [comment]
I just tried this code below and it works fine, can you check if your URL is accessible publicly? Also reboot your iPhone
```
service: notify.mobile_app_brunos_iphone
data:
  message: Vehicle detected in driveway
  title: Vehicle • Driveway
  data:
    attachment:
      url: https://design.home-assistant.io/images/brand/logo.png
    actions:
      - action: MUTE_15_ALL
        title: Mute cams 15 min.
      - action: MUTE_120_ALL
        title: Mute cams 2 hours
```
