### ISSUE TITLE
'show_in_carplay' is an invalid option for 'ios', check: ios->actions->1->show_in_carplay

### ISSUE THREAD

**Issue by townsmcp** [home-assistant/iOS#2562]
Im not sure if I should be reporting this bug here or on the HA GitHub for CORE however the issue is linked. On the https://companion.home-assistant.io/docs/core/actions/#creating-actions-in-home-assistant page, the last 2 lines of config to be entered in HA are:
```
      show_in_carplay: false
      show_in_watch: true
```
When I add these lines of code in HA config I get the following error message when validating config for restart:
```
Invalid config for 'ios' at packages/systems/ios/actions/actions_turn_on_heating.yaml, line 11: 'show_in_carplay' is an invalid option for 'ios', check: ios->actions->1->show_in_carplay
Invalid config for 'ios' at packages/systems/ios/actions/actions_turn_on_heating.yaml, line 12: 'show_in_watch' is an invalid option for 'ios', check: ios->actions->1->show_in_watch
```
The config I have created is:
```
ios:
  actions:
    - name: "Turn On Heating"
      background_color: "#ffd966"
      label:
        text: "Turn On Carport Light"
        color: "#000000"
      icon:
        icon: mdi:thermostat-auto
        color: "#ffffff"
      show_in_carplay: true
      show_in_watch: true
```
(To be clear, I have added this config to its own yaml file as I have my HA split into separate files). If I comment out the last 2 lines, config check works and HA will restart fine and add the new Action to the Companion App.

**iOS device model, version and app version**

**Home Assistant Core Version**
Core 2024.1.6
Supervisor 2024.01.0
Operating System 11.5.rc2
Frontend 20240104.0

**Describe the bug**
HA throws an error when validating config after adding `show_in_carplay` and `show_in_watch`
**To Reproduce**
Add an Action config via HA rather than Companion App.
Validate config before restart.
**Expected behavior**
No error and restart HA without issue. 
New Action to be shown in Companion App
