### ISSUE TITLE
Notifications with images not working in 2024.3 (2024.587) companion beta

### ISSUE THREAD

**Issue by fightingmajor** [home-assistant/iOS#2634]
Model Name:  iPhone 15 Pro Max
Software Version: 17.4
App version: 2024.3 (2024.587)

**Home Assistant Core Version**
2024.3

**Describe the bug**
There is a bug in beta 2024.3 (2024.587) when receiving a notification with an image.  It does not display the preview image on iOS in the notification.  Pressing on the notification does not bring up a bigger image as expected either.  It is also taking 30 secs to receive notficacation as apposed to instantly if no image is attached.  Image preview does show up on Apple Watch.  I reverted back to 2024.3 (2024.580) and this version works fine.  Image preview shows up and pressing notification displays a bigger version of the image.

**To Reproduce**
Developer Tools - Services - Notifications : Send a notification via Mobile_app_iphone, include data image: / media/local/cap.jpg then hit Call Service.  It takes 30 secs to receive notification and image does not show up on iOS.

**Expected behavior**
Receive small image preview in notification and allowing to press and hold notification to bring up a bigger version of the image.

**Comment by bgoncal** [comment]
Thanks for reporting, I checked the internal betas and apparently it was since 581 (not available for public) which comes from this PR https://github.com/home-assistant/iOS/pull/2606

I'll investigate tomorrow

**Comment by bgoncal** [comment]
https://github.com/home-assistant/iOS/pull/2636

**Comment by gieljnssns** [comment]
Actionable notifications also do not work.
```
service: notify.mobile_app_gphone
data:
  message: test
  data:
    actions:
      - action: 16U
        title: Tegen 16u.
      - action: 7U
        title: Tegen 7u.
      - action: ASAP
        title: Zo snel mogelijk.
      - action: NASAP
        title: Het maakt niet uit.
      - action: CHOOSE
        title: Zelf een uur kiezen.
```
![IMG_0314](https://github.com/home-assistant/iOS/assets/17234951/ae7e7e99-1f44-4373-b7af-59d3b51f9799)

the actions do not load.
App version 2024.587
