### ISSUE TITLE
synced actions not updating

### ISSUE THREAD

**Issue by maxandersen** [home-assistant/iOS#2745]
**iOS device model, version and app version**

Model Name: iphone 15 / 11 / apple watch
Software Version: 2024.4
App version: 2024.624

**Home Assistant Core Version**
2024.4

**Describe the bug**
no matter how much I edit, update, delete and restart home assisstant synced actions stay stuck with the values I had several months ago.

**To Reproduce**
have actions working, now go edit the ios/actions in yaml and see that those changes never show up.

**Expected behavior**
that synced actions reflect what is available server side.

**Screenshots**

**Additional context**
fails on home assistant macos app too.

**Comment by bgoncal** [comment]
Please provide your yaml configuration

**Comment by maxandersen** [comment]
sorry thought it was already in, I tried the content from docs with no luck.

Here is my current attempt:


```
ios:
  actions:
    - name: lock_ford
      background_color: "#000000"
      label:
        text: "Lock Ford Toggle"
        color: "#ff0000"
      icon:
        icon: lock
        color: "#ffffff"
    - name: fence_toggle
      background_color: "#000000"
      label:
        text: "Fence Toggle"
        color: "#ff0000"
      icon:
        icon: fence-electric
        color: "#ffffff"
      show_in_watch: true
```

the "lock_ford" is what I started with. Even if I completely remove this block it still shows up.
