### ISSUE TITLE
Support HA's stream component

### ISSUE THREAD

**Issue by pgauret** [home-assistant/iOS#275]
Recent versions of HA introduced a stream component that provides an image preview and live streaming from video cameras. https://www.home-assistant.io/components/stream/

Whilst this works great using a desktop browser, it seems the iOS app cannot stream the live video. Note: live streaming does not appear to work with mobile Safari either.

Not sure of what can be done to the iOS app to enable streaming, or if this requires configuration or changes on the server side.

Relevant extract from my `configuration.yaml` file.

```
stream:
camera:
  - platform: generic
    name: Outside
    still_image_url: http://192.168.1.5/cgi-bin/hi3510/snap.cgi?&-getfile
    stream_source: rtsp://192.168.1.5/11
```

**Comment by zacwest** [comment]
I gave this a try a camera that resembles yours like:

```yaml
stream:
camera:
  - platform: generic
    name: Outside
    still_image_url: http://placekitten.com/1024/768
    stream_source: rtsp://170.93.143.139/rtplive/470011e600ef003a004ee33696235daa
```

Putting this in a `picture-entity` like:

```yaml
type: picture-entity
entity: camera.outside
```

I can view the stream within a card:

![Simulator Screen Shot - iPhone 11 Pro - 2020-06-14 at 23 28 28](https://user-images.githubusercontent.com/74188/84624715-c31ce680-ae96-11ea-92c6-77cf29ded12b.png)

Tapping on the image starts streaming:

![Simulator Screen Shot - iPhone 11 Pro - 2020-06-14 at 23 28 50](https://user-images.githubusercontent.com/74188/84624738-d039d580-ae96-11ea-8af9-728bb61ef7ef.png)

This ticket is old enough that it's possible it was against iOS 12 and that iOS 13 introduced something that makes this better, or perhaps changes since then have improved the situation.
