### ISSUE TITLE
Gifs don't play in Apple Watch notifications

### ISSUE THREAD

**Issue by ofcedwards** [home-assistant/iOS#2816]
**iOS device model, version and app version**

Model Name: iPhone 14 Pro / Apple Watch Series 6
Software Version: iOS 17.5.1 / WatchOS 10.5
App version: 2024.5.1 (2024.688)

**Home Assistant Core Version**
2024.6.2

**Describe the bug**
Gifs attached to notifications do not play on Apple Watch. The image loads, but only the first frame of the gif is shown. The gif correctly plays when the notification is expanded on iPhone.

**To Reproduce**
Send a notification with a gif attached and have your watch set to receive HA notifications your phone receives. Example with gif below.
````
service: notify.phone
data:
  message: test
  title: test
  data:
    attachment:
      url: https://media.giphy.com/media/nR4L10XlJcSeQ/giphy.gif
````

**Expected behavior**
All frames of gif should play and then restart from beginning like they do on iPhone.

**Screenshots**

**Additional context**
