### ISSUE TITLE
iOs Actions not syncing

### ISSUE THREAD

**Issue by wtangofoxtrot** [home-assistant/iOS#2901]
**iOS device model, version and app version**

Model Name: 13mini and 14
Software Version: 17.5.1
App version: 2024.730

**Home Assistant Core Version**

2024.7.2

**Describe the bug**
iOs Actions are setup on the HA server in the configuration.yaml and have been working for atleast 1 year until they stopped ~2weeks ago. No changes were made on the server but all connected iOs devices show an empty list for synced actions as shown in the below screenshot:

**To Reproduce**
- go to Companion app settings >Actions and tap Update server Actions
- Nothing gets synced across from the server

**Expected behavior**
- ios actions are setup in the server's configuration.yaml using https://companion.home-assistant.io/docs/core/actions/ 
- these actions were previously working but stopped across all connected devices by themselves with no server side changes
- re-added dummy action in the configuration.yaml using above documentation and it too did not sync across after restarting the HA server to load the configuration.yaml

**Screenshots**

![353930568-90dfd2af-21a9-475c-8b13-b0651823c2a5](https://github.com/user-attachments/assets/bb6a4177-2a91-4b35-8985-d3781010bc2c)
**Additional context**

Had filed https://github.com/home-assistant/core/issues/122968 but was told to post here as my testing by reverting the HA server to when it was working did not fix the issue indicating this is likely a mobile app issue.
### Example YAML snippet

```yaml
ios:
  actions:
    - name: Fred
      label:
        text: "Hello, World"
      icon:
        icon: earth
      show_in_carplay: false
      show_in_watch: true
    - name: Desk Toggle
      label:
        text: "WTangoFoxtrot's Desk"
      icon:
        icon: Desk
      show_in_watch: true
```
ios companion app logs: [2024-08-02_15.46.20-0700.logs.zip](https://github.com/user-attachments/files/16475912/2024-08-02_15.46.20-0700.logs.zip)
