### ISSUE TITLE
Apple watch icons not working after updating iOS app

### ISSUE THREAD

**Issue by loopy321** [home-assistant/iOS#2921]
**iOS device model, version and app version**
ios vers 16.7.8
ios Watch version 9.6.3
App 2024.7 (2024.730)

**Home Assistant Core Version**
HA Core 2024.8.1

**Describe the bug**
Action icons and colors do not work as before recent upgrade of app.  Currently no icons or colors are shown in the Actions.

**To Reproduce**

**Expected behavior**
Icons and colors as before
**Screenshots**
![Watch ha](https://github.com/user-attachments/assets/842d2f56-2e48-4c69-b736-5687b365567b)

**Additional context**

configuration.yaml : 
```
ios:
  actions:
    - name: Garage door
      background_color: "#ff8000"
      label:
        text: "Garage door"
        color: "#ffffff"
      icon:
        icon: mdi:garage-open
        color: "#ffffff"
    - name: Garage right
      background_color: "#ff8000"
      label:
        text: "Garage right"
        color: "#ffffff"
      icon:
        icon: garage-open
        color: "#ffffff"
    - name: Pause BI Blink
      background_color: "#0000ff"
      label:
        text: "Pause BI/Blink"
        color: "#ffffff"
      icon:
        icon: pause-octagon
        color: "#ffffff"
    - name: Patio_lights
      background_color: "#8000ff"
      label:
        text: "Patio Lights"
        color: "#ffffff"
      icon:
        icon: string-lights
        color: "#ffffff"
```

Log snippet:

https://gist.github.com/loopy321/30a1c219f736a632cbc37c7efdeb9865
