### ISSUE TITLE
Lights in control center don't update their state

### ISSUE THREAD

**Issue by polmum** [home-assistant/iOS#3020]
**iOS device model, version and app version**

Model Name: iPhone 15 pro
Software Version: iOS 18
App version: 20240906.0

**Home Assistant Core Version**
2024.9.1

**Describe the bug**
After adding a light to the control center and toggling it from a different place, the light state of the control center control is not updated.

**To Reproduce**
Add a light to the control center. Turn it on from the control center. Turn it off from the companion app.

**Expected behavior**
The light control in the control center always shows the current state of the light.

**Comment by benjamin-dcs** [comment]
Same issue. I've made a template light as power button for my TV, but doesn't get updated in control centre. The 'light' itself does work in HA

```yaml
- platform: template
  lights: 
    tv_as_light:
      friendly_name: "TV as Light"
      value_template: "{{ states('media_player.lg') }}"
      turn_on:
        action: media_player.turn_on
        target:
          entity_id: media_player.lg
      turn_off:
        action: media_player.turn_off
        target:
          entity_id: media_player.lg
```
