### ISSUE TITLE
Controll Center Widgets do not reflect current state

### ISSUE THREAD

**Issue by Glow91** [home-assistant/iOS#3174]
Model Name: iPhone 12 Pro
Software Version: 18.0
App version: 2024.9.4 (2024.905)

**Home Assistant Core Version**
2024.11.2

**Describe the bug**
If some Lights or Switches has been added to the Control Center for Quick Access, the State of these Entities will not be reflected correctly what make them nearly useless.
So ist possible (almost the case) the Control Center Shows me the Office Light is turned on but it isn't. 
Try to toggle the Light to see the result will end in an inverted behavior of the light. 
It is shown as Off in Control Center but is Turned on, a additional Tab causes it to be shown as On but it is Off

**To Reproduce**
Add some Lights to the Control Center, toggle them from different Sources eg Turn on via a Switch or an Automation. 
Then look to the Control Center while Toggling, you will see that you don't see any change 😄 

**Expected behavior**
The current state of the selected Entity will be shown and will be also updated in real time. 
If this is not Possible this feature is nearly useless.

**Screenshots**
Tricky to show this in a Screenshot. In case it would help I can try to capture a short clip. Let me know please :)

**Comment by bgoncal** [comment]
Please check the current testflight beta if you have time, in there it will reflect the correct state for most cases.
Although it wont reflect realtime state in case you change your light through another way, to reflect it realtime we would need to implement push notifications (since its the only way apple allows to remotely refresh control states) and since we have a cap of 500 notifications per day, this would be not enough to most users with several lights on their homes.

Current workaround, you can create an automation that updates controls through push notification command (`update_widgets `), but dont forget the limit mentioned above: https://companion.home-assistant.io/docs/notifications/notification-commands

**Comment by bgoncal** [comment]
Automation example:

```

alias: Update widgets quando algumas luzes mudarem
description: ""
triggers:
  - trigger: state
    entity_id:
      - light.kitchen_lightstrip
      - light.kitchen_spots
      - light.tv_rack_lights
      - switch.arvore_de_natal
      - cover.living_room_curtain
      - light.elements_4eb4
conditions: []
actions:
  - action: notify.mobile_app_bruno_s_iphone
    metadata: {}
    data:
      message: update_widgets
mode: single

```

**Comment by bgoncal** [comment]
Automation example:

```

alias: Update widgets quando algumas luzes mudarem
description: ""
triggers:
  - trigger: state
    entity_id:
      - light.kitchen_lightstrip
      - light.kitchen_spots
      - light.tv_rack_lights
      - switch.arvore_de_natal
      - cover.living_room_curtain
      - light.elements_4eb4
conditions: []
actions:
  - action: notify.mobile_app_bruno_s_iphone
    metadata: {}
    data:
      message: update_widgets
mode: single

```
