### ISSUE TITLE
Image in Push Notification on Apple WatchOS don't work, when Home Assistant Cloud is off

### ISSUE THREAD

**Issue by rapton** [home-assistant/iOS#3306]
**iOS device model, version and app version**

Model Name: iPhone 13 Pro and Apple Watch Ultra 2
Software Version: Newest (18.1.1 / 11.2)
App version:  2024.12.2 (2024.1058)

**Home Assistant Core Version**
2024.12.5

**Describe the bug**
The push notifications on my Mac and my iPhone shows images and video streams in Push notifications. But my Apple Watch shows "Fehler beim Laden des Anhangs. URLSessionTask failed with error. An SSL error has occurred. [...]". All my devices are on my WLAN and the Home Assistant Server runs on http. 
When I activate the Nabu Casa Home Assistant Cloud, my Apple Watch shows the images in the Push Notifications. 
In the iOS Companion App I have an internal and an external Server configured. When all persons at home, the Home Assistant Cloud is deactivated. 
I think the watch app uses only the  external URL and not the internal URL, when I am at home.

**Comment by leitgab** [comment]
I figured out that `thumbnail.jpg` is not displayed on the Apple Watch in my case, but `snapshot.jpg` is. My assumption is that the resolution of the thumbnail is not sufficient to be displayed on the Apple Watch.

The following configuration shows a preview image on the iPhone and the Apple Watch for me:
```
action: notify.mobile_app_iphone
metadata: {}
data:
  message: "{{trigger.payload_json[\"after\"][\"label\"] | capitalize}} detected"
  data:
    push:
      interruption-level: time-sensitive
    image: >-
      https://home-assistant/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/snapshot.jpg
    tag: "{{trigger.payload_json[\"after\"][\"id\"]}}"
    when: "{{trigger.payload_json[\"after\"][\"start_time\"] | int}}"
    entity_id: >-
      camera.{{trigger.payload_json["after"]["camera"] | replace("-","_") |
      lower}}
  title: >-
    {{trigger.payload_json["after"]["camera"] | replace("_camera","") |
    replace("_"," ") | capitalize}}
```
