### ISSUE TITLE
iBeacon zone not showing in status

### ISSUE THREAD

**Issue by metec22** [home-assistant/iOS#344]
Entering an iBeacon zone does not update the device tracker status to reflect the name of the zone (on build 54). The "Last Update Trigger" sensor correctly shows "iBeacon Region Entered" but the device tracker status stays on "home."

On another device, I am running build 35 and that works fine with the same configuration (on a different HA instance). When I enter an iBeacon zone, the status of the device tracker becomes the name of the zone.

**Comment by bridge-four** [comment]
same issue here after upgrading to v2.0 - did you ever figure this out?

**Comment by bridge-four** [comment]
actually figured this out, here's what I had to change:
- change beacon zones to passive:false
- change each beacon to a unique GPS lat/long value (cannot "nest" these under another zone radius) and set radius to 1
- reset both HA and app. (I did a full reset and deleting/restored app and integration)
- check the app event log to verify working properly. should be good once you see all your zones "zoning" on first boot and that you get successful region enter events that are then reflected on the device_tracker state

It looks like with the v2 update, the region updates are implemented by noticing the beacon on the device, associating that with the predetermined zone's lat/long, and then sending that as a manual location GPS update to HA, which HA will process and assign the device to that zone accordingly.

Hope that helps anyone else with similar issues!

**Comment by SaturnusDJ** [comment]
Currently running this workaround: https://community.home-assistant.io/t/ibeacons-unusable-when-having-a-home-zone-add-subzones/203819/2?u=saturnus

**Comment by CAB426** [comment]
FYI [Beacon Changes](https://github.com/home-assistant/iOS/issues/924)

**Comment by zacwest** [comment]
I believe the above linked issue addresses the latter and the original report looks fixed now.

**Comment by bzumik1** [comment]
Hi, I have following configuration, but entering the zone is not registered for me in HA server even though in mobile app in debug section I see the iBeacon was detected

**iBeacon settings:**
```yaml
zone.vchod:
  beacon:
    uuid: xxxx--xxx-xxx-xxx-xxxx-xxx
    major: 1111111
    minor: 111111
```
**Automation:**
```yaml
alias: Debug - iBeacon pro vchod detekován
description: ""
trigger:
  - platform: event
    event_type: zone_enter
condition:
  - condition: template
    value_template: |
      {{ trigger.event.data.entity_id == 'zone.vchod' }}
action:
  - alias: Pošli upozornění na můj mobil
    service: notify.mobile_app_jakub_iphone
    data:
      title: iBeacon!
      data:
        push:
          sound:
            name: default
            critical: 1
      message: iBeacon pro zónu vchod detekován
mode: single
```
**Mobile app:**
![IMG_B0C072FC7C2B-1](https://github.com/home-assistant/iOS/assets/32042186/b26befe8-3657-4eac-ada2-0f5dae3be495)
