### ISSUE TITLE
iOS Actions are not rendering text,color, or icon on Apple Watch

### ISSUE THREAD

**Issue by pashdown** [home-assistant/iOS#3525]
**iOS device model, version and app version**

Model Name: Apple Watch Series 9
Software Version: watchOS 11.3.1
App version: 2025.3 (2025.1205)

**Home Assistant Core Version**
2025.4.0

**Describe the bug**
None of the text, colors or icons from ios actions are rendering

**To Reproduce**
Setup an action, example:
```
ios:
  actions:
    - name: "GARAGE_CAR_DOOR_TOGGLE"
      background_color: "#413c17"
      label:
        text: "Garage Door"
        color: "#ff9d00"
      icon:
        icon: car-hatchback
        color: "#ff9d00"
      show_in_carplay: false
      show_in_watch: true
      use_custom_colors: true
```

**Expected behavior**
Display text, color, and icon.

**Screenshots**
What the Home Assistant app shows:

![Image](https://github.com/user-attachments/assets/9ed4238b-b526-42db-a0d5-4441068bb26a)

What the Watch shows:

![Image](https://github.com/user-attachments/assets/7e3745f2-b440-40ee-bfc1-50f11da29d51)
