### ISSUE TITLE
Custom CarPlay icons and names do not apply

### ISSUE THREAD

**Issue by remarkov** [home-assistant/iOS#3537]
**iOS device model, version and app version**

Model Name: iPhone 15 Pro Max
Software Version: iOS 18.3.2
App version: 2025.1205

**Home Assistant Core Version**

2025.4.2
**Describe the bug**
Items added in Quick access have an option to override icons and names in DISPLAY TEXT field. The custom settings are shown correctly in the iOS UI but in CarPlay the default name and icon are shown.
**To Reproduce**
Add any item in Quick access for CarPlay, set a custom icon and name, check CarPlay screen.
**Expected behavior**
Name and icon in CarPlay match those setup manually.
**Screenshots**

![Image](https://github.com/user-attachments/assets/a49aa4af-46b7-45ec-95fe-0ac984354545)

![Image](https://github.com/user-attachments/assets/3d3afa45-783c-45a4-a2bc-30808ae1899e)

**Additional context**

I believe it worked some time ago, but not sure which exactly update could have broke this. Could be the latest companion app update.

**Comment by bgoncal** [comment]
Just double checking, the items which don't respect the override are the ones that you added as entities right? (Companion App settings >> CarPlay >> Add item >> entities tab)

The two on the top are correct, right? Are them scripts?

**Comment by remarkov** [comment]
Yes on both questions. The top two are the scripts and they seem to be fine, but their names/icons are not overridden. The two in the bottom are the entities and they do not respect the name/icon settings.

**Comment by bgoncal** [comment]
I'll keep the issue open until the build arrives in testflight

**Comment by remarkov** [comment]
Wow, that was fast! Thanks for your quick response.
As for the scripts, it seems they are also not respecting the custom names (and probably icons), I tried to rename one to test and the CarPlay name did not pick up the change (see screenshots). However, the hint clearly says I should change the name and icon in "in frontend under 'Settings' > 'Automations & scenes' > 'Scripts'" so I am not sure what is the expected behavior there and if the name and icon cannot be changed here in CarPlay settings, why there's such an option?
That's not a big deal though, scripts are easier to manage in UI so there's nothing urgent to fix here.

![Image](https://github.com/user-attachments/assets/fe79d90f-3365-4f26-8ec2-416b9a1ac5b7)

![Image](https://github.com/user-attachments/assets/5563ad94-56b6-4fc8-8b8c-cc5acc0f65ed)

For your reference, here is the YAML config of one of the scripts (they are almost identical to each other with minor difference in the action sequence)

```yaml
alias: Car arriving
sequence:
  - alias: Open gates if closed
    if:
      - condition: state
        entity_id: binary_sensor.gates_open_close_sensor_contact
        state: "off"
    then:
      - device_id: 94f8aea11b43ed3f29dd082829bade14
        domain: button
        entity_id: cf7ee6e34b04b17d80158f43f46ac96d
        type: press
  - alias: Open garage door if closed
    if:
      - condition: state
        entity_id: binary_sensor.garage_door_open_close_sensor_contact
        state: "off"
    then:
      - action: cover.open_cover
        metadata: {}
        data: {}
        target:
          entity_id: cover.garage_door
  - wait_for_trigger:
      - trigger: state
        entity_id:
          - binary_sensor.gates_io_module_input_3
        from: "on"
        for:
          hours: 0
          minutes: 0
          seconds: 5
        to: "off"
    timeout:
      hours: 0
      minutes: 10
      seconds: 0
    alias: Wait for car to pass gates
  - device_id: 94f8aea11b43ed3f29dd082829bade14
    domain: button
    entity_id: cf7ee6e34b04b17d80158f43f46ac96d
    type: press
    alias: Close gates
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
    enabled: true
  - action: cover.close_cover
    metadata: {}
    data: {}
    target:
      entity_id: cover.garage_door
    alias: Close garage door
description: ""
icon: mdi:car-arrow-left
```

**Comment by bgoncal** [comment]
Thanks for the overview, I have just submited the app for testflight, soon it will become available as `2025.4`

**Comment by bgoncal** [comment]
Can you check the latest testflight build?

**Comment by remarkov** [comment]
I wish I could test, but Testflight says the beta is full so I can't install :(

**Comment by bgoncal** [comment]
I just opened up a few extra seats

**Comment by remarkov** [comment]
Thanks, got it installed, will test and report back soon

**Comment by remarkov** [comment]
The fix worked perfectly well, the icons and names are properly displayed in the CarPlay now! 

As a side note, I added another script and noticed that it shows sub-label "Off" for done reason (see screenshot). I have no idea where it comes from and it does not make much sense as the script just sequentially sends two button presses so there's nothing to be on or off. I don't see this anywhere in the UI apart from CarPlay. Do you have any ideas what that could be and how it can be removed?

Here's the script for reference:
```
sequence:
  - device_id: 94f8aea11b43ed3f29dd082829bade14
    domain: button
    entity_id: cf7ee6e34b04b17d80158f43f46ac96d
    type: press
  - device_id: 23778364d9b883498ca0d3cc29b5c706
    domain: button
    entity_id: 4468afc10edccc95fc0e58f731dccfd9
    type: press
alias: Another script
description: ""
icon: mdi:signal-variant
```
![image](https://github.com/user-attachments/assets/564eaddd-a452-42e7-8166-756871c68ff6)
