### ISSUE TITLE
sensor.iphone_step is a string not a value

### ISSUE THREAD

**Issue by whoo** [home-assistant/iOS#3680]
Hi,

In my experimentation with iOS application.
App version: 2025.5
“Steps” appears as a string instead of an integer so I can not graph or build automation based on value.

**Screenshots**
<img width="923" alt="Image" src="https://github.com/user-attachments/assets/d5a108e4-e9aa-4bc1-98f9-7f46e9b43743" />

It seems a bug, It should be numeric (have a unit).

I found a workaround to add a graph-able value by adding in configuration.yaml

```yaml
template:
   - sensor:
       - name: ip14step
         unique_id: ip14stepcalc
         state: >
            {{ '%d'|int(states('sensor.ip14p_steps')) }}
         state_class: measurement  
```

tks,
W.
