### ISSUE TITLE
Webcams - Autoplay startup Home assistant 2.0 app iOS

### ISSUE THREAD

**Issue by diogopms** [home-assistant/iOS#496]
First of all: Thank you for the great app/work, I'm using it for 2 years without any problems.

In my Lovelace YAML config, I have some streaming webcams embedded using an iframe.

After upgrading to 2.0, every time that I start the homeassistant the streams start playing at the
same time.

**ios app version: 2.0.0 (69)**
**lovelace config:**
``` 
- badges: []
    cards:
      - entities:
          - entity: automation.beep_beep_when_alarm_is_pending_arm_disarmed
        type: entities
      - cards:
          - aspect_ratio: 60%
            title: Webcams
            type: iframe
            url: 'https://server.diogoserrano.com/saopedro.html'
        type: vertical-stack
    path: others
    title: Others
```
**Webcam public URL: https://server.diogoserrano.com/saopedro.html**

Please check this video with the behaviour:
https://youtu.be/gUr1Zv6-22o

Note: In the previous version, I didn't have this issue :) and It only happens if you set the **iframe** in the `default_view`. 

Thanks for the hard work 🙏 
Regards
Diogo
