### ISSUE TITLE
Camera notifications only 4:3

### ISSUE THREAD

**Issue by olbjan** [home-assistant/iOS#513]
Camera notifications of cameras streaming 16:9 content is rendered as 4:3. This aesthetic issue is I believe ever since the start of notifications.

**Comment by Tangston311** [comment]
Seeing the same issue here - I have a 640x360 MJPEG stream that's getting distorted (initially posted here: https://community.home-assistant.io/t/distorted-camera-feed-in-ios-notification/174380


**Undistored View:**
![14416fe89d13e17c1a1312089372c689ffc40a46](https://user-images.githubusercontent.com/47066967/75270581-05bb9580-57b8-11ea-9653-8d02fe212241.jpeg)

**View in iOS Notification:**
![b413b070dd376614e33cc7560d8eb097d931ff83](https://user-images.githubusercontent.com/47066967/75270586-08b68600-57b8-11ea-9779-44e3a6b77ac1.jpeg)


My camera setup:

```
camera:
  - platform: mjpeg
    mjpeg_url: http://<#ipaddress>:<#port>/wps-cgi/mjpg/video.cgi?camera=1&resolution=640x360&username=#####&password=#####
    name: Porch
```

My config:

```
- alias: Front Door Sensor Tripped
  trigger:
    - platform: state
      entity_id: sensor.zone_001
      to: 'Violated'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: alarm_control_panel.alarm_com
        state: 'armed_away'
      - condition: state
        entity_id: alarm_control_panel.alarm_com
        state: 'armed_home'
  action:
    service: notify.mobile_app_iphone
    data:
      message: "Front Door Sensor Tripped!"
      data:
        attachment:
          content-type: jpeg
        push:
          sound:
            name: "Update.caf"
            critical: 1
            volume: 1.0
          category: camera
        entity_id: camera.porch
```
