### ISSUE TITLE
Mobile Phone device_tracker entity status fails to update

### ISSUE THREAD

**Issue by polarburn** [home-assistant/iOS#563]
## The problem
The device_tracker.[name] entity for my iPhone 11 fails to have its status (GPS location) updated.  Status is currently unknown.  I've deleted the integration for the mobile device and subsequently re-added it by connecting to Home Assistant with the mobile app.  This results in the same issue.  Locations Services is set to Always for the Home Assistant iOS app.

## Environment
  I am running Home Assistant 0.106.5 on a Raspberry Pi 4b.  I recently updated but don't recall if the issue existed in the previous version.
- Home Assistant release with the issue: Home Assistant 0.106.5
- Last working Home Assistant release (if known): Unknown
- Operating environment (Hass.io/Docker/Windows/etc.): HassOS 3.12 on Pi 4b
- Integration causing this issue: Mobile App
- Link to integration documentation on our website: https://www.home-assistant.io/integrations/mobile_app/

## Problem-relevant `configuration.yaml`

My configuration.yaml (very basic as I am just setting up a fresh instance)

```yaml
default_config:

frontend:
  themes: !include_dir_merge_named themes/

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 4x.xxxxxxxxxxxxxx
  longitude: -9x.xxxxxxxxxxxxxx
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 961
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include customize.yaml

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
```

The only item I can think of that is configured that would have an impact on my mobile device is the following in my customize.yaml

zone.home:
  icon: mdi:home-heart
  radius: '300'

```yaml

```

## Traceback/Error logs
Here are log events showing errors related to the problem from home-assistant.log

2020-03-08 22:01:38 ERROR (MainThread) [homeassistant.util.logging] Exception in update_data when dispatching 'mobile_app_location_update_f9xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdc': ({'gps': [4x.xxxxxxxxxxxxxx, -9x.xxxxxxxxxxxxxx], 'vertical_accuracy': 10, 'gps_accuracy': 65, 'altitude': 297.99951171875, 'battery': 65},)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mobile_app/device_tracker.py", line 156, in update_data
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 297, in async_write_ha_state
    self._async_write_ha_state()  # type: ignore
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    state = self.state
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/config_entry.py", line 100, in state
    self.hass, self.latitude, self.longitude, self.location_accuracy
  File "/usr/src/homeassistant/homeassistant/components/zone/__init__.py", line 109, in async_active_zone
    within_zone = zone_dist - radius < zone.attributes[ATTR_RADIUS]
TypeError: '<' not supported between instances of 'float' and 'str'

I see the above text occur several times per hour in the home-assistant.log

```txt

```

## Additional information
I was home all weekend and within range of my network.  Even today I have been home for several hours and several sensor values for my phone have not updated.  I can access the mobile app on my network without issue.
