### ISSUE TITLE
Feature Req: Url open Ios app

### ISSUE THREAD

**Issue by askusbloodfist** [home-assistant/iOS#573]
I know that you can open Waze from the action menu. 
But as far as i can tell theres no way to open any other app with a action notify. 
I have read the dokuments and cant find anything about it. 

For example if my door is not lock i can get a notis about it. But if i want to lock it i have to open my Alarm app and close it. 

It would be nice to be able to klick the notice and then the app opens.

**Comment by robbiet480** [comment]
I believe this is already possible as it was added at fee7fa834ccd8b88558bee5bf0d8c3123b09a11a.

Something like this should work, I think:

```yaml
automation:
  - alias: Notify of Motion
    trigger:
      ...
    action:
      service: notify.mobile_app_<your_device_id_here>
      data:
        title: "Motion Detected in Backyard"
        message: "Someone might be in the backyard."
        data:
          url: 'https://google.com' # action when clicking main notification
```

Let me know!

@TomBrien can docs get updated to show this example?
