### ISSUE TITLE
Clicks not registered on iPad Pro in certain circumstances

### ISSUE THREAD

**Issue by fmonday** [home-assistant/iOS#582]
**iOS device model, version and app version**

Model Name: iPad Pro (11 inch)
Software Version: 13.4.1
App version: 0.108.9/2019.1

**Home Assistant Core Version**

0.109.0

**Describe the bug**
Icon clicks/button toggles are not registered by the HA Companion app on an iPad Pro under certain circumstances. However, using the same iPad, these clicks register normally when interacting with HA through a browser (both Safari and Chrome). Additionally the issue appears to only be present on the iPad, as the issues are NOT replicated on an iPhone XI pro max running the same iOS & HA Companion app versions. 

**To Reproduce**
- pressing on icons in the header to switch views/dashboards usually requires at least two presses to register. This is complicated by the fact that frequently after a page refresh or upon returning to the app after using something else, the icons disappear until the page is moved a little bit. Icons in the sidebar also frequently require several tries to respond but don't disappear. 
- sliders on certain cards (such as a thermostat) are tricky to grab and can require several tries. 
- create a ```custom:button-card``` which requires confirmation; the button does not respond at all. Other custom buttons work fine. 
```
          - type: custom:button-card
            icon: 'mdi:restart'
            name: lovelace
            template: scenes
            aspect_ratio: 1.3/1
            confirmation:
              text: '[[[ return `Really do that?` ]]]'
            tap_action:
              action: call-service
              service: frontend.reload_themes
              haptic: success
```
**Expected behavior**
Icons/buttons toggle as expected. 
**Screenshots**
<-- If applicable, add screenshots to help explain your problem. -->

**Additional context**
Long-standing issues
