### ISSUE TITLE
Setting Firebase Cloud Messaging not persistent.

### ISSUE THREAD

**Issue by oppsig** [home-assistant/iOS#595]
**iOS device model, version and app version**

Model Name:iPhone SE
Software Version: 13.5
App version: 2.0.0 (69)

**Home Assistant Core Version**
 
0.110.4

**Describe the bug**
My problem is two fold.
I'm trying to send notifications to my ios phone.
I've set `ios: ` in configuration.yaml. Restarted home assistant and ios is downloaded.

Then I've tried to enable Firebase Cloud Messaging.
But the setting Firebase Cloud Messaging is not persistant.
Not sure if this is what is causing my issue.

Not recieving any notifications from home assistant.

**To Reproduce**
Open Home Assistant companion app.
Enable Firebase Cloud Messaging. Close app. Open app. Firebase Cloud Messaging.

**Expected behavior**
Firebase Cloud Messaging remains enabled.

**Screenshots**
<-- If applicable, add screenshots to help explain your problem. -->
[](url)

**Additional context**

**Comment by TomBrien** [comment]
Can you post a minimal example of the code you’re using to send the notification and have you confirmed the appropriate `notify.mobile_app...` service exists

**Comment by oppsig** [comment]
automations.yaml
```
- id: '1591001757541'
  alias: notifytest
  description: ''
  trigger:
  - at: 07:09:00
    platform: time
  condition: []
  action:
  - data:
      message: test test test
      title: test
    service: notify.mobile_app_no_xxxx_iphone_xxxx
```

Confirm like this? (Developer Tools > Services)
![screenshot_2020-06-02-071414](https://user-images.githubusercontent.com/480951/83482746-5cb0c500-a4a1-11ea-9056-6b21de6e1a76.png)
