### ISSUE TITLE
App frozen with no UI after iOS 13.5.1 update

### ISSUE THREAD

**Issue by scstraus** [home-assistant/iOS#669]
**iOS device model, version and app version**

Model Name: iPhone X
Software Version: iOS 13.5.1
App version: 2020.1

**Home Assistant Core Version**

.111.3

**Describe the bug**

iOS app doesn't display the UI directly after iOS update 13.5.1. Cannot access sidebar menu, cannot access any UI elements. Was working fine on same hass version prior to 13.5.1 update. UI displays correctly in all other browsers on windows, iOS, fireos, and macos including fully kiosk, chrome, firefox, and iOS safari. Nothing I can find helps, quitting, rebooting, etc.

**To Reproduce**

Open the app.

**Expected behavior**

A UI

**Screenshots**

![image](https://user-images.githubusercontent.com/7644023/84893865-3cd3f080-b0a0-11ea-9290-224abee2e994.png)

**Additional context**
[My full config is published here if you need any context](https://github.com/scstraus/home-assistant-config)

**Comment by zacwest** [comment]
Are you able to open the menu and get to the App Configuration? Being able to take a look at the logs would be very helpful in this situation.

**Comment by scstraus** [comment]
No, I couldn't open the app configuration either.. But I figured out what happened. It wasn't the update after all, but some lovelace code that I've had working fine for the last 20 or so releases that just now decided to blow up only the iOS app. This is the offending code. It doesn't like the vertical-stack-in card nested inside a vertical stack. If I have them nested like this the iOS app blows up (and only the iOS app, all other browsers work):


```
  - type: vertical-stack
    cards:

    - type: 'custom:weather-card-chart'
      title: Weather / Air Quality
      weather: weather.openweathermap
      sun: sun.sun
      mode: hourly

    - type: custom:vertical-stack-in-card
      cards:
      - type: "custom:button-card"
        name: Hlubočepy
        styles:
          name:
            - color: var(--ha-card-header-color)
          card:
            - padding: 8px 0px

      - type: custom:air-visual-card 
        air_pollution_level: sensor.hlubocepy_air_pollution
        air_quality_index: sensor.hlubocepy_air_quality
        main_pollutant: sensor.u_s_main_pollutant_2
        hide_title: true
        svg_location: "/local/icons/aqi_icons"

    - type: custom:vertical-stack-in-card
      cards:

      - type: "custom:button-card"
        name: Home
        styles:
          name:
            - color: var(--ha-card-header-color)
          card:
            - padding: 8px 0px

      - type: custom:air-visual-card 
        air_pollution_level: sensor.home_air_pollution
        air_quality_index: sensor.home_air_quality
        main_pollutant: sensor.u_s_main_pollutant_2
        hide_title: true
        svg_location: "/local/icons/aqi_icons"
```

But if I take out the enclosing vertical stack like so, the iOS app works fine:

```
#  - type: vertical-stack
#    cards:

  - type: 'custom:weather-card-chart'
    title: Weather / Air Quality
    weather: weather.openweathermap
    sun: sun.sun
    mode: hourly

  - type: custom:vertical-stack-in-card
    cards:
    - type: "custom:button-card"
      name: Hlubočepy
      styles:
        name:
          - color: var(--ha-card-header-color)
        card:
          - padding: 8px 0px

    - type: custom:air-visual-card 
      air_pollution_level: sensor.hlubocepy_air_pollution
      air_quality_index: sensor.hlubocepy_air_quality
      main_pollutant: sensor.u_s_main_pollutant_2
      hide_title: true
      svg_location: "/local/icons/aqi_icons"

  - type: custom:vertical-stack-in-card
    cards:

    - type: "custom:button-card"
      name: Home
      styles:
        name:
          - color: var(--ha-card-header-color)
        card:
          - padding: 8px 0px

    - type: custom:air-visual-card 
      air_pollution_level: sensor.home_air_pollution
      air_quality_index: sensor.home_air_quality
      main_pollutant: sensor.u_s_main_pollutant_2
      hide_title: true
      svg_location: "/local/icons/aqi_icons"

```
