### ISSUE TITLE
Beacon - Changes to handle passive zones

### ISSUE THREAD

**Issue by CAB426** [home-assistant/iOS#924]
Passive Zones are not currently being respected on the iOS app.  According to the Core documents, passive zones are not used for the device tracker and are only used to trigger automations.  The current behavior of the app is to disregard the passive flag and set the device tracker to that zone.  I would like to see that app respect the passive flag and trigger a custom event when the zone is entered/exited.  Something simple like zone_enter/zone.enter and zone_leave/zone.leave with the data including the zone entity_id.  This would enable easier room presence, or subzones within a zone, without the need for additional apps (OwnTracks).

```
{
    "event_type": "zone_enter",
    "data": {
        "entity_id": "zone.front_door"
    }
}
```
```
{
    "event_type": "zone_leave",
    "data": {
        "entity_id": "zone.front_door"
    }
}
```
These events would be easy to pick up in automations and Node-Red.

Automations Example:
```
trigger:
    platform: event
    event_type: zone_enter
  condition:
    condition: template
    value_template: >
      {{ trigger.event.data.entity_id == 'zone.front_door' }}
```
