### ISSUE TITLE
iOS Companion App doesn’t support percent encoded URLs

### ISSUE THREAD

**Issue by flyboy013** [home-assistant/iOS#930]
**iOS device model, version and app version**

Model Name: iPhone 11 Pro Max
Software Version: 13.5.1
App version: 2020.5.2 (1)

**Home Assistant Core Version**

HA Core Version 0.114.1

**Describe the bug**

iOS Companion App will not open URLs (via button-card tap_action) if the URL contains percent encoding (ie. %020 between tokens).  See issue at: https://community.home-assistant.io/t/ios-companion-app-doesnt-support-percent-encoded-urls/179138

URLs open correctly when "Open Links In" is set to Safari, but not when set to Google Chrome.

**To Reproduce**

Sample Code: 

```
title: HA Testing
views:

  - title: URL Path Test
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:

              - type: 'custom:button-card'
                tap_action:
                  action: url
                  url_path: https://www.google.com/search?q=home+assistant
                
                color_type: icon
                show_label: true
                label: This Works
                
              - type: 'custom:button-card'
                tap_action:
                  action: url
                  url_path: https://www.google.com/search?q=home%20assistant
                color_type: icon
                show_label: true
                label: This Doesn't Work 
```
**Expected behavior**

The specified URL should be opened in Google Chrome app.

**Screenshots**

**Additional context**
