### ISSUE TITLE
Support TTS on notify service

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/iOS#972]
**Is your feature request related to a problem? Please describe.**
When I'm on my Mac, I am typically using noise cancelling headphones and listening to music. So it's sometimes hard or impossible to hear TTS announcements on my Google Home or Alexa, or hear my phone vibrating for a new notification. 

It would be pretty useful if you could leverage your Mac's built-in text to speech to send a TTS. Would be especially useful for important notifications that you don't want to miss ("intruder detected at back door!").

**Describe the solution you'd like**
Basic example, uses the default system voice and speaking rate under System Prefs -> Accessibility -> Spoken Content:

```
    action:
      service: notify.mobile_app_<your_macbook_pro>_tts
      data:
        message: "This message will be spoken out loud by your Mac. Awesome!"
```
This would be equivalent to typing `say "This message will be spoken out loud by your Mac. Awesome!"` in the Terminal.

Full example (optional), change the voice and speaking rate:

```
    action:
      service: notify.mobile_app_<your_macbook_pro>_tts
      data:
        message: "This message will be spoken out loud by your Mac. Awesome!"
        data:
          voice: Alex
          speaking_rate: 240
```

This would be equivalent to typing `say -v Alex "This message will be spoken out loud by your Mac. Awesome!" -r 240` in the Terminal.

**Describe alternatives you've considered**

Rather than creating a secondary notify service like the examples above, it could be part of the default one service, and the user would just specify `type: tts` to make it speak rather than sending a text notification.

```
      service: notify.mobile_app_<your_macbook_pro>
      data:
        message: "This message will be spoken out loud by your Mac. Awesome!"
        data:
          type: tts
          voice: Samantha  # optional
          speaking_rate: 270  # optional
```

**Additional context**
